# Generated by Django 6.0.5 on 2026-05-21 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RunSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=20)),
                ('session_type', models.CharField(choices=[('free', 'Free Run'), ('planned', 'Planned Run')], default='free', max_length=20)),
                ('total_distance_m', models.FloatField(default=0)),
                ('total_duration_s', models.IntegerField(default=0)),
                ('avg_pace_s_per_km', models.IntegerField(default=0)),
                ('best_pace_s_per_km', models.IntegerField(default=0)),
                ('calories_burned', models.FloatField(default=0)),
                ('elevation_gain_m', models.FloatField(default=0)),
                ('avg_heart_rate', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RunPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('altitude_m', models.FloatField(blank=True, null=True)),
                ('accuracy_m', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('speed_m_s', models.FloatField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='runs.runsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='runsession',
            index=models.Index(fields=['user', 'status'], name='runs_runses_user_id_aebd60_idx'),
        ),
        migrations.AddIndex(
            model_name='runsession',
            index=models.Index(fields=['user', 'session_type'], name='runs_runses_user_id_a6d545_idx'),
        ),
        migrations.AddIndex(
            model_name='runpoint',
            index=models.Index(fields=['session', 'timestamp'], name='runs_runpoi_session_d737ec_idx'),
        ),
    ]
