# Generated by Django 6.0.5 on 2026-06-07 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='runsession',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='run_ended_after_started'),
        ),
        migrations.AddConstraint(
            model_name='runsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'completed'), _negated=True), ('ended_at__isnull', False), _connector='OR'), name='run_completed_has_ended_at'),
        ),
    ]
