# Generated by Django 6.0.5 on 2026-06-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0002_runsession_run_ended_after_started_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runsession',
            name='cumplimiento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runsession',
            name='feedback_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runsession',
            name='feedback_notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runsession',
            name='molestias',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='runsession',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runsession',
            name='rpe_real',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
