# Generated by Django 6.0.5 on 2026-06-21 21:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0003_runsession_cumplimiento_runsession_feedback_at_and_more'),
        ('workouts', '0022_exercise_add_creado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RunnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_pace_s_km', models.IntegerField(blank=True, null=True)),
                ('vo2_estimado', models.FloatField(blank=True, null=True)),
                ('fc_max', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(220)])),
                ('fc_reposo', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(110)])),
                ('fc_max_es_estimada', models.BooleanField(default=True)),
                ('volumen_semanal_base_km', models.FloatField(blank=True, null=True)),
                ('zonas', models.JSONField(blank=True, default=dict)),
                ('fuente_baseline', models.CharField(choices=[('historial', 'Estimado de Free Runs'), ('declarado', 'Tiempo de carrera declarado'), ('time_trial', 'Time-trial guiado'), ('manual', 'Editado a mano'), ('cold_start', 'Sin datos — provisional')], default='cold_start', max_length=20)),
                ('confianza', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='baja', max_length=10)),
                ('n_runs_baseline', models.IntegerField(default=0)),
                ('fecha_calculo', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='runner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'runner_profiles',
            },
        ),
        migrations.CreateModel(
            name='RunningPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_tipo', models.CharField(choices=[('fitness_general', 'Fitness general (sin fecha)'), ('5k', '5K'), ('10k', '10K'), ('21k', 'Media maratón'), ('42k', 'Maratón'), ('otra', 'Otra distancia')], default='fitness_general', max_length=20)),
                ('meta_distancia_km', models.FloatField(blank=True, null=True)),
                ('meta_fecha', models.DateField(blank=True, null=True)),
                ('fase_actual', models.CharField(choices=[('base', 'Base'), ('build', 'Construcción'), ('peak', 'Pico'), ('taper', 'Taper'), ('recovery', 'Recuperación/Transición')], default='base', max_length=12)),
                ('semana_actual', models.PositiveSmallIntegerField(default=1)),
                ('total_semanas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('km_objetivo_semana', models.FloatField(default=0)),
                ('dias_semana', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('dias_preferidos', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateField()),
                ('week_start', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='running_plans', to='workouts.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='running_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'running_plans',
            },
        ),
        migrations.CreateModel(
            name='PlannedRunSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_sesion', models.CharField(choices=[('easy', 'Easy/Recovery'), ('long', 'Long run'), ('tempo', 'Tempo/Umbral'), ('vo2', 'Intervalos VO2máx'), ('fartlek', 'Fartlek'), ('hills', 'Cuestas'), ('progressive', 'Progresivo'), ('strides', 'Series/Strides'), ('recovery', 'Recuperación'), ('rest', 'Descanso'), ('cross', 'Cross-training')], max_length=12)),
                ('es_calidad', models.BooleanField(default=False)),
                ('zona_principal', models.CharField(blank=True, max_length=4)),
                ('duracion_objetivo_min', models.IntegerField(blank=True, null=True)),
                ('distancia_objetivo_km', models.FloatField(blank=True, null=True)),
                ('rpe_target', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('estructura_fases', models.JSONField(blank=True, default=dict)),
                ('respuesta_ia', models.JSONField(blank=True, default=dict)),
                ('prompt_usado', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('ajustada', 'Ajustada por readiness'), ('completada', 'Completada'), ('saltada', 'Saltada')], default='planificada', max_length=12)),
                ('readiness_snapshot', models.JSONField(blank=True, default=dict)),
                ('ajuste_aplicado', models.CharField(blank=True, max_length=40)),
                ('generacion_ms', models.IntegerField(blank=True, null=True)),
                ('tokens_in', models.IntegerField(blank=True, null=True)),
                ('tokens_out', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_origin', to='runs.runsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_runs', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='runs.runningplan')),
            ],
            options={
                'db_table': 'planned_run_sessions',
                'ordering': ['fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='runningplan',
            index=models.Index(fields=['user', 'is_active'], name='running_pla_user_id_b22e41_idx'),
        ),
        migrations.AddConstraint(
            model_name='runningplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_active_running_plan_per_user'),
        ),
        migrations.AddIndex(
            model_name='plannedrunsession',
            index=models.Index(fields=['user', 'fecha'], name='planned_run_user_id_616444_idx'),
        ),
        migrations.AddIndex(
            model_name='plannedrunsession',
            index=models.Index(fields=['plan', 'estado'], name='planned_run_plan_id_378eba_idx'),
        ),
        migrations.AddConstraint(
            model_name='plannedrunsession',
            constraint=models.UniqueConstraint(fields=('plan', 'fecha'), name='unique_planned_run_per_plan_day'),
        ),
    ]
