# Generated by Django 6.0.5 on 2026-06-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0004_runnerprofile_runningplan_plannedrunsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runsession',
            name='is_trail',
            field=models.BooleanField(default=False),
        ),
    ]
