# Generated by Django 6.0.5 on 2026-08-31 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0005_runsession_is_trail'),
    ]

    operations = [
        migrations.AddField(
            model_name='runsession',
            name='local_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
