# Generated by Django 5.2.15 on 2026-07-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0005_runsession_is_trail"),
    ]

    operations = [
        migrations.AddField(
            model_name="runsession",
            name="gps_resumen",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="runsession",
            name="puntos_purgados",
            field=models.BooleanField(default=False),
        ),
    ]
