# Generated by Django 6.0.5 on 2026-08-31 13:10

import django.core.validators
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count, Q


def _dedupe_run_points(apps, schema_editor):
    """Antes de crear unique_point_per_session_timestamp: si algún reintento
    de red ya duplicó puntos GPS en producción (el bug que este mismo cambio
    corrige hacia adelante), el AddConstraint de abajo fallaría al aplicar
    sobre datos existentes que lo violan. Se queda con la fila de menor id
    por (session, timestamp) — son filas idénticas en lat/lng/etc, producto
    del mismo reintento, no se pierde información real."""
    RunPoint = apps.get_model('runs', 'RunPoint')
    dupes = (
        RunPoint.objects.values('session_id', 'timestamp')
        .annotate(n=Count('id'))
        .filter(n__gt=1)
    )
    for d in dupes:
        ids = list(
            RunPoint.objects
            .filter(session_id=d['session_id'], timestamp=d['timestamp'])
            .order_by('id')
            .values_list('id', flat=True)
        )
        RunPoint.objects.filter(id__in=ids[1:]).delete()


def _clamp_run_session_ranges(apps, schema_editor):
    """Antes de agregar los CheckConstraint de rango: clampea/anula cualquier
    valor existente fuera de rango para que el AddConstraint no falle sobre
    datos ya en producción que nunca fueron validados a nivel de BD (antes
    solo RunFeedbackSerializer los validaba, no el modelo)."""
    RunSession = apps.get_model('runs', 'RunSession')
    RunSession.objects.filter(total_distance_m__lt=0).update(total_distance_m=0)
    RunSession.objects.filter(total_duration_s__lt=0).update(total_duration_s=0)
    RunSession.objects.filter(avg_pace_s_per_km__lt=0).update(avg_pace_s_per_km=0)
    RunSession.objects.filter(best_pace_s_per_km__lt=0).update(best_pace_s_per_km=0)
    RunSession.objects.filter(calories_burned__lt=0).update(calories_burned=0)
    RunSession.objects.filter(elevation_gain_m__lt=0).update(elevation_gain_m=0)
    RunSession.objects.exclude(
        Q(rpe_real__isnull=True) | Q(rpe_real__gte=1, rpe_real__lte=10)
    ).update(rpe_real=None)
    RunSession.objects.exclude(
        Q(rating__isnull=True) | Q(rating__gte=1, rating__lte=5)
    ).update(rating=None)
    RunSession.objects.exclude(
        Q(cumplimiento__isnull=True) | Q(cumplimiento__gte=0, cumplimiento__lte=100)
    ).update(cumplimiento=None)


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0006_runsession_local_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedrunsession',
            name='narracion_fallback',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='runsession',
            name='avg_pace_s_per_km',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='runsession',
            name='best_pace_s_per_km',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='runsession',
            name='calories_burned',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='runsession',
            name='cumplimiento',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='runsession',
            name='elevation_gain_m',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='runsession',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='runsession',
            name='rpe_real',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='runsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='runsession',
            name='total_distance_m',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='runsession',
            name='total_duration_s',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='runsession',
            index=models.Index(fields=['user', 'started_at'], name='runs_runses_user_id_19b2e5_idx'),
        ),
        # Limpieza defensiva de datos existentes ANTES de los AddConstraint de
        # abajo — ver docstrings de cada función. Sin esto, si producción ya
        # tiene una fila que violaría un constraint nuevo, el AddConstraint
        # falla al aplicar y el deploy entero se cae (entrypoint.sh corre
        # `migrate` bloqueante, ver backend/CLAUDE.md).
        migrations.RunPython(_dedupe_run_points, _noop),
        migrations.RunPython(_clamp_run_session_ranges, _noop),
        migrations.AddConstraint(
            model_name='runpoint',
            constraint=models.UniqueConstraint(fields=('session', 'timestamp'), name='unique_point_per_session_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='runsession',
            constraint=models.CheckConstraint(condition=models.Q(('total_distance_m__gte', 0)), name='run_distance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='runsession',
            constraint=models.CheckConstraint(condition=models.Q(('total_duration_s__gte', 0)), name='run_duration_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='runsession',
            constraint=models.CheckConstraint(condition=models.Q(('avg_pace_s_per_km__gte', 0)), name='run_avg_pace_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='runsession',
            constraint=models.CheckConstraint(condition=models.Q(('best_pace_s_per_km__gte', 0)), name='run_best_pace_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='runsession',
            constraint=models.CheckConstraint(condition=models.Q(('calories_burned__gte', 0)), name='run_calories_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='runsession',
            constraint=models.CheckConstraint(condition=models.Q(('elevation_gain_m__gte', 0)), name='run_elevation_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='runsession',
            constraint=models.CheckConstraint(condition=models.Q(('rpe_real__isnull', True), models.Q(('rpe_real__gte', 1), ('rpe_real__lte', 10)), _connector='OR'), name='run_rpe_real_in_range'),
        ),
        migrations.AddConstraint(
            model_name='runsession',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='run_rating_in_range'),
        ),
        migrations.AddConstraint(
            model_name='runsession',
            constraint=models.CheckConstraint(condition=models.Q(('cumplimiento__isnull', True), models.Q(('cumplimiento__gte', 0), ('cumplimiento__lte', 100)), _connector='OR'), name='run_cumplimiento_in_range'),
        ),
    ]
