# Generated by Django 6.0.5 on 2026-08-31 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0007_plannedrunsession_narracion_fallback_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RunTypeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sesion', models.CharField(choices=[('easy', 'Easy/Recovery'), ('long', 'Long run'), ('tempo', 'Tempo/Umbral'), ('vo2', 'Intervalos VO2máx'), ('fartlek', 'Fartlek'), ('hills', 'Cuestas'), ('progressive', 'Progresivo'), ('strides', 'Series/Strides'), ('recovery', 'Recuperación'), ('rest', 'Descanso'), ('cross', 'Cross-training')], max_length=12)),
                ('veces_realizado', models.IntegerField(default=0)),
                ('rpe_promedio_real', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rpe_promedio_target', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cumplimiento_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ultima_vez', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_type_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'run_type_profiles',
                'indexes': [models.Index(fields=['user', 'tipo_sesion'], name='run_type_pr_user_id_ddcdb2_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'tipo_sesion'), name='unique_run_type_profile_per_user')],
            },
        ),
    ]
