# Generated by Django 6.0.5 on 2026-06-09 19:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('titulo', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('video', 'Video'), ('texto', 'Texto'), ('quiz', 'Quiz')], default='texto', max_length=10)),
                ('contenido', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('duracion_min', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'academy_lessons',
                'ordering': ['module', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('resumen', models.CharField(blank=True, help_text='Una línea de gancho.', max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(blank=True, help_text='Temática del curso (entrenamiento, nutrición, salud, movilidad…).', max_length=80)),
                ('nivel', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='principiante', max_length=20)),
                ('portada', models.TextField(blank=True)),
                ('duracion_estimada_min', models.PositiveIntegerField(default=0)),
                ('publicado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_academy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='activa', max_length=20)),
                ('progreso', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completado_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academy.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_enrollments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=24, unique=True)),
                ('emitido_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificado', to='academy.enrollment')),
            ],
            options={
                'db_table': 'academy_certificates',
                'ordering': ['-emitido_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=True)),
                ('completado_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones_progreso', to='academy.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academy.lesson')),
            ],
            options={
                'db_table': 'academy_lesson_progress',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('titulo', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='academy.course')),
            ],
            options={
                'db_table': 'academy_modules',
                'ordering': ['course', 'orden'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='academy.module'),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=180)),
                ('puntaje_aprobacion', models.PositiveSmallIntegerField(default=70, help_text='Porcentaje mínimo para aprobar el quiz.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='academy.lesson')),
            ],
            options={
                'db_table': 'academy_quizzes',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('enunciado', models.TextField()),
                ('tipo', models.CharField(choices=[('opcion_unica', 'Opción única'), ('opcion_multiple', 'Opción múltiple'), ('verdadero_falso', 'Verdadero / Falso')], default='opcion_unica', max_length=20)),
                ('opciones', models.JSONField(blank=True, default=list)),
                ('respuestas_correctas', models.JSONField(blank=True, default=list)),
                ('puntos', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='academy.quiz')),
            ],
            options={
                'db_table': 'academy_questions',
                'ordering': ['quiz', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestas', models.JSONField(blank=True, default=dict)),
                ('detalle', models.JSONField(blank=True, default=list)),
                ('puntaje', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('aprobado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='academy.enrollment')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='academy.quiz')),
            ],
            options={
                'db_table': 'academy_quiz_attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['publicado', '-created_at'], name='academy_cou_publica_44583b_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['categoria'], name='academy_cou_categor_50aee0_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', '-created_at'], name='academy_enr_student_070e61_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['enrollment', 'completado'], name='academy_les_enrollm_b0b1a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('enrollment', 'lesson')},
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', 'orden'], name='academy_mod_course__12d743_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'orden'], name='academy_les_module__148526_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['quiz', 'orden'], name='academy_que_quiz_id_6c783b_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['enrollment', 'quiz', '-created_at'], name='academy_qui_enrollm_909699_idx'),
        ),
    ]
