# Generated by Django 6.0.5 on 2026-06-10 02:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='acredita_renovacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='carga_horaria_h',
            field=models.PositiveIntegerField(default=0, help_text='Carga horaria oficial del curso, en horas.'),
        ),
        migrations.AddField(
            model_name='course',
            name='disciplina',
            field=models.CharField(choices=[('general', 'General'), ('futbol', 'Fútbol'), ('futsal', 'Futsal'), ('futbol_playa', 'Fútbol Playa'), ('arqueros', 'Entrenadores de Arqueros'), ('preparacion_fisica', 'Preparación Física')], default='general', help_text='Disciplina federada del curso (fútbol, futsal, arqueros…) o "general".', max_length=24),
        ),
        migrations.AddField(
            model_name='course',
            name='licencia',
            field=models.CharField(blank=True, choices=[('', 'Sin licencia (curso/taller)'), ('C', 'Licencia C'), ('B', 'Licencia B'), ('A', 'Licencia A'), ('PRO', 'Licencia PRO')], default='', help_text='Nivel de Licencia CONMEBOL que otorga (C/B/A/PRO). Vacío si es un curso/taller sin licencia.', max_length=4),
        ),
        migrations.AddField(
            model_name='course',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('semipresencial', 'Semipresencial (blended)')], default='virtual', max_length=16),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['disciplina', 'licencia'], name='academy_cou_discipl_6ad4b5_idx'),
        ),
    ]
