# Generated by Django 6.0.5 on 2026-06-10 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_course_conmebol_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='entregable_tipo',
            field=models.CharField(blank=True, choices=[('texto', 'Análisis escrito'), ('video', 'Video (URL)'), ('planificacion', 'Planificación')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='lesson',
            name='fecha_en_vivo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='tipo',
            field=models.CharField(choices=[('video', 'Video'), ('texto', 'Texto'), ('quiz', 'Quiz'), ('en_vivo', 'Sesión en vivo'), ('practica', 'Práctica presencial'), ('entregable', 'Entregable')], default='texto', max_length=10),
        ),
        migrations.CreateModel(
            name='CourseBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('nombre', models.CharField(max_length=80)),
                ('icono', models.CharField(blank=True, help_text='Emoji de la insignia.', max_length=8)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insignias', to='academy.course')),
                ('lesson', models.ForeignKey(help_text='Lección cuyo completado otorga la insignia.', on_delete=django.db.models.deletion.CASCADE, related_name='insignias', to='academy.lesson')),
            ],
            options={
                'db_table': 'academy_course_badges',
                'ordering': ['course', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='EarnedBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otorgada_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academy.coursebadge')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insignias_obtenidas', to='academy.enrollment')),
            ],
            options={
                'db_table': 'academy_earned_badges',
                'ordering': ['otorgada_at'],
                'unique_together': {('enrollment', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('estado', models.CharField(choices=[('enviada', 'Enviada (en revisión)'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='enviada', max_length=12)),
                ('feedback', models.TextField(blank=True, help_text='Comentario del instructor al revisar.')),
                ('revisado_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='academy.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='academy.lesson')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_submissions',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['lesson', 'estado'], name='academy_sub_lesson__9aa60f_idx')],
                'unique_together': {('enrollment', 'lesson')},
            },
        ),
    ]
