# Generated by Django 6.0.5 on 2026-07-02 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_lesson_tipo_audio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('racha_actual', models.PositiveIntegerField(default=0)),
                ('mejor_racha', models.PositiveIntegerField(default=0)),
                ('ultima_actividad', models.DateField(blank=True, null=True)),
                ('congelado_hasta', models.DateField(blank=True, null=True)),
                ('freezes_disponibles', models.PositiveSmallIntegerField(default=0)),
                ('freezes_usados', models.PositiveIntegerField(default=0)),
                ('racha_en_riesgo', models.PositiveIntegerField(default=0)),
                ('recuperable_hasta', models.DateTimeField(blank=True, null=True)),
                ('total_rachas_rotas', models.PositiveIntegerField(default=0)),
                ('puntos_totales', models.PositiveIntegerField(default=0)),
                ('logros', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academy_streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_streaks',
            },
        ),
        migrations.CreateModel(
            name='AcademyActivityDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('origen', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_activity_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_activity_days',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['user', '-fecha'], name='academy_act_user_id_f250f3_idx')],
                'unique_together': {('user', 'fecha')},
            },
        ),
    ]
