# Generated by Django 6.0.5 on 2026-07-03 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_academystreak_academyactivityday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.SlugField(max_length=60, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('icono', models.CharField(blank=True, help_text='Emoji de la insignia.', max_length=8)),
                ('criterio_tipo', models.CharField(choices=[('escuela_completada', 'Escuela completada'), ('streak_dias', 'Racha de estudio (días)'), ('primera_leccion', 'Primera lección completada'), ('curso_completado', 'Curso completado')], max_length=20)),
                ('criterio_valor', models.PositiveIntegerField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('criterio_curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academy.course')),
                ('criterio_escuela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academy.school')),
            ],
            options={
                'db_table': 'academy_badges',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AcademyEarnedBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otorgada_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academy.academybadge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_insignias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_badges_earned',
                'ordering': ['-otorgada_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
