# Generated by Django 6.0.5 on 2026-07-03 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_academybadge_academyearnedbadge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('estado', models.CharField(choices=[('visible', 'Visible'), ('oculto_ia', 'Oculto (IA)'), ('oculto_reportes', 'Oculto (reportes)'), ('oculto_manual', 'Oculto (manual)')], db_index=True, default='visible', max_length=20)),
                ('moderacion_resultado', models.JSONField(blank=True, null=True)),
                ('reportes_count', models.PositiveIntegerField(default=0)),
                ('respuestas_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_posts', to='academy.course')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to='academy.school')),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_posts', to='academy.module')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to='academy.tenant')),
            ],
            options={
                'db_table': 'academy_community_posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('estado', models.CharField(choices=[('visible', 'Visible'), ('oculto_ia', 'Oculto (IA)'), ('oculto_reportes', 'Oculto (reportes)'), ('oculto_manual', 'Oculto (manual)')], db_index=True, default='visible', max_length=20)),
                ('moderacion_resultado', models.JSONField(blank=True, null=True)),
                ('votos_count', models.PositiveIntegerField(default=0)),
                ('reportes_count', models.PositiveIntegerField(default=0)),
                ('es_mejor_respuesta', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_replies', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='academy.communitypost')),
            ],
            options={
                'db_table': 'academy_community_replies',
                'ordering': ['-es_mejor_respuesta', '-votos_count', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='communitypost',
            name='mejor_respuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academy.communityreply'),
        ),
        migrations.CreateModel(
            name='CommunityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('spam', 'Spam'), ('ofensivo', 'Ofensivo'), ('fuera_de_tema', 'Fuera de tema'), ('otro', 'Otro')], max_length=20)),
                ('detalle', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='academy.communitypost')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='academy.communityreply')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_reportes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_community_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='academy.communityreply')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_votos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_community_votes',
            },
        ),
        migrations.AddIndex(
            model_name='communityreply',
            index=models.Index(fields=['post', 'estado'], name='academy_com_post_id_ac36e5_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['escuela', 'estado'], name='academy_com_escuela_c1ae56_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['curso', 'estado'], name='academy_com_curso_i_fd8eaf_idx'),
        ),
        migrations.AddConstraint(
            model_name='communityreport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('post__isnull', False), ('reply__isnull', True)), models.Q(('post__isnull', True), ('reply__isnull', False)), _connector='OR'), name='community_report_exactamente_un_target'),
        ),
        migrations.AddConstraint(
            model_name='communityreport',
            constraint=models.UniqueConstraint(condition=models.Q(('post__isnull', False)), fields=('post', 'reportado_por'), name='community_report_unico_por_post_y_usuario'),
        ),
        migrations.AddConstraint(
            model_name='communityreport',
            constraint=models.UniqueConstraint(condition=models.Q(('reply__isnull', False)), fields=('reply', 'reportado_por'), name='community_report_unico_por_reply_y_usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='communityvote',
            unique_together={('reply', 'usuario')},
        ),
    ]
