# Generated by Django 6.0.5 on 2026-07-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_communitypost_communityreply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academybadge',
            name='criterio_tipo',
            field=models.CharField(choices=[('escuela_completada', 'Escuela completada'), ('streak_dias', 'Racha de estudio (días)'), ('primera_leccion', 'Primera lección completada'), ('curso_completado', 'Curso completado'), ('respuestas_utiles', 'Respuestas de Comunidad marcadas como mejor respuesta')], max_length=20),
        ),
    ]
