# Generated by Django 6.0.5 on 2026-07-03 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_alter_academybadge_criterio_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='es_gratuito',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AcademySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada'), ('vencida', 'Vencida'), ('pago_fallido', 'Pago fallido')], default='activa', max_length=20)),
                ('plan_tipo', models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual')], default='mensual', max_length=20)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_renovacion', models.DateField(blank=True, null=True)),
                ('proveedor_pago', models.CharField(blank=True, default='', max_length=40)),
                ('referencia_externa', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academy_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_subscriptions',
            },
        ),
    ]
