# Generated by Django 6.0.5 on 2026-07-03 15:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_module_es_gratuito_academysubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('migrada_en', models.DateTimeField(blank=True, null=True)),
                ('migrada_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_anonymous_sessions',
            },
        ),
        migrations.CreateModel(
            name='AnonymousProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academy.lesson')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='academy.anonymoussession')),
            ],
            options={
                'db_table': 'academy_anonymous_progress',
                'unique_together': {('session', 'lesson')},
            },
        ),
    ]
