# Generated by Django 6.0.5 on 2026-07-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0013_reestructura_escuelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='descripcion_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='resumen_en',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='course',
            name='titulo_en',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='module',
            name='descripcion_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='module',
            name='titulo_en',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='school',
            name='descripcion_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='school',
            name='nombre_en',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
