# Generated by Django 6.0.5 on 2026-07-06 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0014_locale_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('documento', 'Documento'), ('video', 'Video'), ('plantilla', 'Plantilla'), ('guia', 'Guía'), ('infografia', 'Infografía'), ('herramienta', 'Herramienta'), ('enlace', 'Enlace')], default='documento', max_length=16)),
                ('titulo', models.CharField(max_length=200)),
                ('titulo_en', models.CharField(blank=True, default='', max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('descripcion_en', models.TextField(blank=True, default='')),
                ('fuente', models.CharField(blank=True, max_length=160)),
                ('url', models.URLField(max_length=500)),
                ('miniatura', models.TextField(blank=True)),
                ('etiquetas', models.JSONField(blank=True, default=list)),
                ('es_gratuito', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('vistas', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_biblioteca', to='academy.course')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_biblioteca', to='academy.school')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_biblioteca', to='academy.tenant')),
            ],
            options={
                'db_table': 'academy_library_resources',
                'ordering': ['-destacado', 'orden', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LibraryFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca_favoritos', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='academy.libraryresource')),
            ],
            options={
                'db_table': 'academy_library_favorites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='libraryresource',
            index=models.Index(fields=['tenant', 'activo', '-created_at'], name='academy_lib_tenant__0b8e30_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryresource',
            index=models.Index(fields=['tipo'], name='academy_lib_tipo_f57f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryresource',
            index=models.Index(fields=['school'], name='academy_lib_school__e00057_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryresource',
            index=models.Index(fields=['course'], name='academy_lib_course__6a392b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='libraryfavorite',
            unique_together={('user', 'resource')},
        ),
    ]
