# Generated by Django 6.0.5 on 2026-07-09 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0016_reestructura_7_escuelas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('resumen', models.CharField(blank=True, help_text='Bajada para la tarjeta y el SEO.', max_length=300)),
                ('contenido', models.TextField(blank=True)),
                ('portada', models.TextField(blank=True)),
                ('etiquetas', models.JSONField(blank=True, default=list)),
                ('publicado', models.BooleanField(default=False)),
                ('publicado_en', models.DateTimeField(blank=True, null=True)),
                ('vistas', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='academy.school')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='academy.tenant')),
            ],
            options={
                'db_table': 'academy_blog_posts',
                'ordering': ['-publicado_en', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'publicado', '-publicado_en'], name='academy_blo_tenant__5d1672_idx'), models.Index(fields=['school'], name='academy_blo_school__63e410_idx'), models.Index(fields=['autor'], name='academy_blo_autor_i_06cbb0_idx')],
            },
        ),
    ]
