# Generated by Django 6.0.5 on 2026-07-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0017_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='meta_descripcion',
            field=models.CharField(blank=True, help_text='Meta description SEO (~150-155 caracteres). Vacío → usa `resumen`.', max_length=170),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_titulo',
            field=models.CharField(blank=True, help_text='<title> SEO (~55-60 caracteres). Vacío → usa `titulo`.', max_length=70),
        ),
    ]
