# Generated by Django 6.0.5 on 2026-07-10 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0018_blogpost_meta_descripcion_blogpost_meta_titulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=300)),
                ('respuesta', models.TextField()),
                ('pregunta_en', models.CharField(blank=True, default='', max_length=300)),
                ('respuesta_en', models.TextField(blank=True, default='')),
                ('categoria', models.CharField(blank=True, max_length=80)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('publicado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs_soporte', to='academy.tenant')),
            ],
            options={
                'db_table': 'academy_support_faqs',
                'ordering': ['orden', 'id'],
                'indexes': [models.Index(fields=['tenant', 'publicado'], name='academy_sup_tenant__52e3c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_admin', models.BooleanField(default=False)),
                ('texto', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_soporte', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_soporte', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_soporte', to='academy.tenant')),
            ],
            options={
                'db_table': 'academy_support_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['tenant', 'student', 'created_at'], name='academy_sup_tenant__976902_idx')],
            },
        ),
    ]
