# Generated by Django 6.0.5 on 2026-07-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0020_seed_support_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='puntos',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
