# Generated by Django 6.0.5 on 2026-07-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0022_seed_lesson_puntos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academysubscription',
            name='plan_tipo',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], default='mensual', max_length=20),
        ),
    ]
