# Generated by Django 6.0.5 on 2026-07-15 18:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0023_alter_academysubscription_plan_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'competencies',
                'db_table': 'academy_competencies',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='LessonCompetencyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('fuente', models.CharField(choices=[('ia', 'IA'), ('manual', 'Manual')], default='ia', max_length=10)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='academy.competency')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='academy.lesson')),
            ],
            options={
                'db_table': 'academy_lesson_competency_tags',
                'indexes': [models.Index(fields=['competency', 'lesson'], name='academy_les_compete_948bfd_idx')],
                'unique_together': {('lesson', 'competency')},
            },
        ),
        migrations.CreateModel(
            name='StudentCompetencyMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('evidencia_n', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academy.competency')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_competency_mastery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'student competency mastery',
                'db_table': 'academy_student_competency_mastery',
                'indexes': [models.Index(fields=['student', 'nivel'], name='academy_stu_student_8ea438_idx')],
                'unique_together': {('student', 'competency')},
            },
        ),
    ]
