# Generated by Django 6.0.5 on 2026-07-07 02:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('contacto', models.CharField(blank=True, default='', max_length=150)),
                ('notas_pago', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'promos_influencer',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CodigoPromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo_descuento', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('fijo', 'Monto fijo')], default='porcentaje', max_length=20)),
                ('valor_descuento', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('comision_monto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('activo', models.BooleanField(default=True)),
                ('usos_maximos', models.IntegerField(blank=True, null=True)),
                ('valido_hasta', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos', to='promos.influencer')),
            ],
            options={
                'db_table': 'promos_codigo_promocional',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_tipo', models.CharField(choices=[('mensual', 'Mensual'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=20)),
                ('precio_lista', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comision_influencer', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('notas_admin', models.TextField(blank=True, default='')),
                ('comision_pagada', models.BooleanField(default=False)),
                ('fecha_pago_comision', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmada_at', models.DateTimeField(blank=True, null=True)),
                ('codigo_promocional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='promos.codigopromocional')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_suscripcion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'promos_solicitud_suscripcion',
                'ordering': ['-created_at'],
            },
        ),
    ]
