# Generated by Django 6.0.5 on 2026-07-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigopromocional',
            name='producto',
            field=models.CharField(choices=[('zyfit_pro', 'Zyfit Pro'), ('academy_pro', 'Zyfit Academy Pro')], default='zyfit_pro', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudsuscripcion',
            name='producto',
            field=models.CharField(choices=[('zyfit_pro', 'Zyfit Pro'), ('academy_pro', 'Zyfit Academy Pro')], default='zyfit_pro', max_length=20),
        ),
    ]
