# Generated by Django 6.0.5 on 2026-07-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0002_codigopromocional_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudsuscripcion',
            name='plan_tipo',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=20),
        ),
    ]
