# Generated by Django 6.0.5 on 2026-07-11 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0003_alter_solicitudsuscripcion_plan_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudGestionSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(choices=[('zyfit_pro', 'Zyfit Pro'), ('academy_pro', 'Zyfit Academy Pro')], default='zyfit_pro', max_length=20)),
                ('tipo', models.CharField(choices=[('cancelar', 'Cancelar'), ('cambiar_plan', 'Cambiar de plan')], max_length=20)),
                ('plan_tipo_deseado', models.CharField(blank=True, choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesada', 'Procesada')], default='pendiente', max_length=20)),
                ('notas_admin', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('procesada_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_gestion_suscripcion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'promos_solicitud_gestion_suscripcion',
                'ordering': ['-created_at'],
            },
        ),
    ]
