from django.core.management.base import BaseCommand, CommandError
from workouts.models import Exercise


EXERCISES = [
    # ── BODYWEIGHT ─────────────────────────────────────────────────────────────
    {
        'nombre': 'Flexión de brazos',
        'patron_movimiento': 'empuje_horizontal',
        'musculos_primarios': ['pectoral', 'tríceps'],
        'musculos_secundarios': ['hombro anterior', 'core'],
        'equipamiento': [],
        'dificultad': 'principiante',
        'contraindicaciones': ['hombro', 'muñeca'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Flexión pike',
        'patron_movimiento': 'empuje_vertical',
        'musculos_primarios': ['deltoides', 'tríceps'],
        'musculos_secundarios': ['pectoral superior'],
        'equipamiento': [],
        'dificultad': 'intermedio',
        'contraindicaciones': ['hombro', 'muñeca'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Flexión diamante',
        'patron_movimiento': 'empuje_horizontal',
        'musculos_primarios': ['tríceps', 'pectoral'],
        'musculos_secundarios': ['hombro anterior'],
        'equipamiento': [],
        'dificultad': 'intermedio',
        'contraindicaciones': ['hombro', 'muñeca', 'codo'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Fondos en banco',
        'patron_movimiento': 'empuje_horizontal',
        'musculos_primarios': ['tríceps', 'pectoral'],
        'musculos_secundarios': ['hombro'],
        'equipamiento': [],
        'dificultad': 'principiante',
        'contraindicaciones': ['hombro', 'codo'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Remo invertido',
        'patron_movimiento': 'jale_horizontal',
        'musculos_primarios': ['dorsal', 'bíceps', 'romboides'],
        'musculos_secundarios': ['core'],
        'equipamiento': [],
        'dificultad': 'principiante',
        'contraindicaciones': ['hombro'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Sentadilla libre',
        'patron_movimiento': 'sentadilla',
        'musculos_primarios': ['cuádriceps', 'glúteos'],
        'musculos_secundarios': ['isquiotibiales', 'core'],
        'equipamiento': [],
        'dificultad': 'principiante',
        'contraindicaciones': ['rodilla'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Sentadilla búlgara',
        'patron_movimiento': 'sentadilla',
        'musculos_primarios': ['cuádriceps', 'glúteos'],
        'musculos_secundarios': ['isquiotibiales'],
        'equipamiento': [],
        'dificultad': 'intermedio',
        'contraindicaciones': ['rodilla', 'cadera'],
        'bilateral': False,
        'es_compuesto': True,
    },
    {
        'nombre': 'Zancada',
        'patron_movimiento': 'sentadilla',
        'musculos_primarios': ['cuádriceps', 'glúteos'],
        'musculos_secundarios': ['isquiotibiales', 'core'],
        'equipamiento': [],
        'dificultad': 'principiante',
        'contraindicaciones': ['rodilla'],
        'bilateral': False,
        'es_compuesto': True,
    },
    {
        'nombre': 'Zancada inversa',
        'patron_movimiento': 'sentadilla',
        'musculos_primarios': ['cuádriceps', 'glúteos'],
        'musculos_secundarios': ['isquiotibiales'],
        'equipamiento': [],
        'dificultad': 'principiante',
        'contraindicaciones': ['rodilla'],
        'bilateral': False,
        'es_compuesto': True,
    },
    {
        'nombre': 'Step-up peso corporal',
        'patron_movimiento': 'sentadilla',
        'musculos_primarios': ['cuádriceps', 'glúteos'],
        'musculos_secundarios': ['isquiotibiales'],
        'equipamiento': [],
        'dificultad': 'principiante',
        'contraindicaciones': ['rodilla'],
        'bilateral': False,
        'es_compuesto': True,
    },
    {
        'nombre': 'Puente de glúteos',
        'patron_movimiento': 'bisagra',
        'musculos_primarios': ['glúteos', 'isquiotibiales'],
        'musculos_secundarios': ['core', 'lumbar'],
        'equipamiento': [],
        'dificultad': 'principiante',
        'contraindicaciones': [],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Hip thrust peso corporal',
        'patron_movimiento': 'bisagra',
        'musculos_primarios': ['glúteos'],
        'musculos_secundarios': ['isquiotibiales', 'core'],
        'equipamiento': [],
        'dificultad': 'principiante',
        'contraindicaciones': [],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Peso muerto rumano peso corporal',
        'patron_movimiento': 'bisagra',
        'musculos_primarios': ['isquiotibiales', 'glúteos'],
        'musculos_secundarios': ['lumbar'],
        'equipamiento': [],
        'dificultad': 'intermedio',
        'contraindicaciones': ['lumbar'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Buenos días peso corporal',
        'patron_movimiento': 'bisagra',
        'musculos_primarios': ['isquiotibiales', 'lumbar'],
        'musculos_secundarios': ['glúteos'],
        'equipamiento': [],
        'dificultad': 'intermedio',
        'contraindicaciones': ['lumbar', 'cuello'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Curl nórdico',
        'patron_movimiento': 'bisagra',
        'musculos_primarios': ['isquiotibiales'],
        'musculos_secundarios': ['glúteos'],
        'equipamiento': [],
        'dificultad': 'avanzado',
        'contraindicaciones': ['rodilla'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Plancha frontal',
        'patron_movimiento': 'core',
        'musculos_primarios': ['core', 'recto abdominal'],
        'musculos_secundarios': ['hombro', 'glúteos'],
        'equipamiento': [],
        'dificultad': 'principiante',
        'contraindicaciones': ['lumbar', 'hombro', 'muñeca'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Plancha lateral',
        'patron_movimiento': 'core',
        'musculos_primarios': ['oblicuos', 'core'],
        'musculos_secundarios': ['hombro', 'glúteos'],
        'equipamiento': [],
        'dificultad': 'principiante',
        'contraindicaciones': ['hombro', 'muñeca'],
        'bilateral': False,
        'es_compuesto': False,
    },
    {
        'nombre': 'Hollow body hold',
        'patron_movimiento': 'core',
        'musculos_primarios': ['recto abdominal', 'flexores cadera'],
        'musculos_secundarios': ['core'],
        'equipamiento': [],
        'dificultad': 'intermedio',
        'contraindicaciones': [],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Dead bug',
        'patron_movimiento': 'core',
        'musculos_primarios': ['core', 'transverso abdominal'],
        'musculos_secundarios': ['lumbar estabilizadores'],
        'equipamiento': [],
        'dificultad': 'principiante',
        'contraindicaciones': ['lumbar'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Escalador',
        'patron_movimiento': 'cardio',
        'musculos_primarios': ['core', 'hombro'],
        'musculos_secundarios': ['cuádriceps', 'glúteos'],
        'equipamiento': [],
        'dificultad': 'principiante',
        'contraindicaciones': ['hombro', 'muñeca'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Elevación de piernas',
        'patron_movimiento': 'core',
        'musculos_primarios': ['recto abdominal', 'flexores cadera'],
        'musculos_secundarios': ['core'],
        'equipamiento': [],
        'dificultad': 'principiante',
        'contraindicaciones': ['lumbar'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Crunch abdominal',
        'patron_movimiento': 'core',
        'musculos_primarios': ['recto abdominal'],
        'musculos_secundarios': ['oblicuos'],
        'equipamiento': [],
        'dificultad': 'principiante',
        'contraindicaciones': ['cuello', 'lumbar'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Russian twist peso corporal',
        'patron_movimiento': 'core',
        'musculos_primarios': ['oblicuos'],
        'musculos_secundarios': ['recto abdominal'],
        'equipamiento': [],
        'dificultad': 'principiante',
        'contraindicaciones': ['lumbar'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Superman',
        'patron_movimiento': 'movilidad',
        'musculos_primarios': ['lumbar', 'glúteos'],
        'musculos_secundarios': ['isquiotibiales'],
        'equipamiento': [],
        'dificultad': 'principiante',
        'contraindicaciones': [],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Bird dog',
        'patron_movimiento': 'core',
        'musculos_primarios': ['core', 'lumbar estabilizadores'],
        'musculos_secundarios': ['glúteos'],
        'equipamiento': [],
        'dificultad': 'principiante',
        'contraindicaciones': ['muñeca'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Burpee',
        'patron_movimiento': 'cardio',
        'musculos_primarios': ['cuerpo completo'],
        'musculos_secundarios': ['core', 'hombro'],
        'equipamiento': [],
        'dificultad': 'intermedio',
        'contraindicaciones': ['hombro', 'muñeca', 'rodilla'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Sentadilla con salto',
        'patron_movimiento': 'cardio',
        'musculos_primarios': ['cuádriceps', 'glúteos'],
        'musculos_secundarios': ['isquiotibiales'],
        'equipamiento': [],
        'dificultad': 'intermedio',
        'contraindicaciones': ['rodilla', 'tobillo'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Jumping jack',
        'patron_movimiento': 'cardio',
        'musculos_primarios': ['cuerpo completo'],
        'musculos_secundarios': [],
        'equipamiento': [],
        'dificultad': 'principiante',
        'contraindicaciones': [],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Rodillas altas',
        'patron_movimiento': 'cardio',
        'musculos_primarios': ['cuádriceps', 'core'],
        'musculos_secundarios': ['glúteos'],
        'equipamiento': [],
        'dificultad': 'principiante',
        'contraindicaciones': [],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Elevación de talones peso corporal',
        'patron_movimiento': 'cardio',
        'musculos_primarios': ['pantorrilla'],
        'musculos_secundarios': ['sóleo'],
        'equipamiento': [],
        'dificultad': 'principiante',
        'contraindicaciones': ['tobillo'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Pistol squat',
        'patron_movimiento': 'sentadilla',
        'musculos_primarios': ['cuádriceps', 'glúteos'],
        'musculos_secundarios': ['core'],
        'equipamiento': [],
        'dificultad': 'avanzado',
        'contraindicaciones': ['rodilla', 'tobillo'],
        'bilateral': False,
        'es_compuesto': True,
    },
    {
        'nombre': 'Estiramiento flexor de cadera',
        'patron_movimiento': 'movilidad',
        'musculos_primarios': ['flexores cadera'],
        'musculos_secundarios': ['cadera'],
        'equipamiento': [],
        'dificultad': 'principiante',
        'contraindicaciones': [],
        'bilateral': False,
        'es_compuesto': False,
    },
    {
        'nombre': 'Cat-cow',
        'patron_movimiento': 'movilidad',
        'musculos_primarios': ['columna'],
        'musculos_secundarios': ['core'],
        'equipamiento': [],
        'dificultad': 'principiante',
        'contraindicaciones': [],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Rotación torácica',
        'patron_movimiento': 'movilidad',
        'musculos_primarios': ['dorsal', 'core'],
        'musculos_secundarios': [],
        'equipamiento': [],
        'dificultad': 'principiante',
        'contraindicaciones': [],
        'bilateral': False,
        'es_compuesto': False,
    },
    {
        'nombre': 'World greatest stretch',
        'patron_movimiento': 'movilidad',
        'musculos_primarios': ['cuerpo completo'],
        'musculos_secundarios': [],
        'equipamiento': [],
        'dificultad': 'principiante',
        'contraindicaciones': [],
        'bilateral': False,
        'es_compuesto': False,
    },
    {
        'nombre': 'Estiramiento 90-90 cadera',
        'patron_movimiento': 'movilidad',
        'musculos_primarios': ['cadera', 'glúteos'],
        'musculos_secundarios': [],
        'equipamiento': [],
        'dificultad': 'principiante',
        'contraindicaciones': ['rodilla'],
        'bilateral': False,
        'es_compuesto': False,
    },
    # ── BARRAS ─────────────────────────────────────────────────────────────────
    {
        'nombre': 'Dominada prona',
        'patron_movimiento': 'jale_vertical',
        'musculos_primarios': ['dorsal', 'bíceps'],
        'musculos_secundarios': ['romboides', 'core'],
        'equipamiento': ['Barras'],
        'dificultad': 'avanzado',
        'contraindicaciones': ['hombro', 'codo'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Dominada supina',
        'patron_movimiento': 'jale_vertical',
        'musculos_primarios': ['dorsal', 'bíceps'],
        'musculos_secundarios': ['romboides'],
        'equipamiento': ['Barras'],
        'dificultad': 'intermedio',
        'contraindicaciones': ['hombro', 'codo'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Sentadilla con barra',
        'patron_movimiento': 'sentadilla',
        'musculos_primarios': ['cuádriceps', 'glúteos'],
        'musculos_secundarios': ['isquiotibiales', 'lumbar', 'core'],
        'equipamiento': ['Barras'],
        'dificultad': 'intermedio',
        'contraindicaciones': ['rodilla', 'lumbar', 'hombro'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Sentadilla frontal con barra',
        'patron_movimiento': 'sentadilla',
        'musculos_primarios': ['cuádriceps'],
        'musculos_secundarios': ['glúteos', 'core'],
        'equipamiento': ['Barras'],
        'dificultad': 'avanzado',
        'contraindicaciones': ['rodilla', 'muñeca'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Peso muerto convencional',
        'patron_movimiento': 'bisagra',
        'musculos_primarios': ['isquiotibiales', 'glúteos', 'lumbar'],
        'musculos_secundarios': ['trapecios', 'core'],
        'equipamiento': ['Barras'],
        'dificultad': 'intermedio',
        'contraindicaciones': ['lumbar'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Peso muerto rumano con barra',
        'patron_movimiento': 'bisagra',
        'musculos_primarios': ['isquiotibiales', 'glúteos'],
        'musculos_secundarios': ['lumbar'],
        'equipamiento': ['Barras'],
        'dificultad': 'intermedio',
        'contraindicaciones': ['lumbar'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Hip thrust con barra',
        'patron_movimiento': 'bisagra',
        'musculos_primarios': ['glúteos'],
        'musculos_secundarios': ['isquiotibiales', 'core'],
        'equipamiento': ['Barras'],
        'dificultad': 'intermedio',
        'contraindicaciones': ['lumbar'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Buenos días con barra',
        'patron_movimiento': 'bisagra',
        'musculos_primarios': ['isquiotibiales', 'lumbar'],
        'musculos_secundarios': ['glúteos'],
        'equipamiento': ['Barras'],
        'dificultad': 'avanzado',
        'contraindicaciones': ['lumbar', 'cuello'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Press de banca con barra',
        'patron_movimiento': 'empuje_horizontal',
        'musculos_primarios': ['pectoral', 'tríceps'],
        'musculos_secundarios': ['hombro anterior', 'core'],
        'equipamiento': ['Barras'],
        'dificultad': 'intermedio',
        'contraindicaciones': ['hombro'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Press inclinado con barra',
        'patron_movimiento': 'empuje_horizontal',
        'musculos_primarios': ['pectoral superior', 'tríceps'],
        'musculos_secundarios': ['hombro anterior'],
        'equipamiento': ['Barras'],
        'dificultad': 'intermedio',
        'contraindicaciones': ['hombro'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Press militar con barra',
        'patron_movimiento': 'empuje_vertical',
        'musculos_primarios': ['deltoides', 'tríceps'],
        'musculos_secundarios': ['core', 'trapecios'],
        'equipamiento': ['Barras'],
        'dificultad': 'intermedio',
        'contraindicaciones': ['hombro', 'lumbar'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Remo con barra',
        'patron_movimiento': 'jale_horizontal',
        'musculos_primarios': ['dorsal', 'bíceps', 'romboides'],
        'musculos_secundarios': ['lumbar', 'core'],
        'equipamiento': ['Barras'],
        'dificultad': 'intermedio',
        'contraindicaciones': ['lumbar'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Remo Pendlay',
        'patron_movimiento': 'jale_horizontal',
        'musculos_primarios': ['dorsal', 'bíceps'],
        'musculos_secundarios': ['lumbar', 'core'],
        'equipamiento': ['Barras'],
        'dificultad': 'avanzado',
        'contraindicaciones': ['lumbar'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Curl de bíceps con barra',
        'patron_movimiento': 'jale_vertical',
        'musculos_primarios': ['bíceps'],
        'musculos_secundarios': ['braquial'],
        'equipamiento': ['Barras'],
        'dificultad': 'principiante',
        'contraindicaciones': ['codo'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Press cerrado con barra',
        'patron_movimiento': 'empuje_horizontal',
        'musculos_primarios': ['tríceps', 'pectoral'],
        'musculos_secundarios': ['hombro'],
        'equipamiento': ['Barras'],
        'dificultad': 'intermedio',
        'contraindicaciones': ['hombro', 'codo'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Encogimientos con barra',
        'patron_movimiento': 'jale_vertical',
        'musculos_primarios': ['trapecios'],
        'musculos_secundarios': ['cuello'],
        'equipamiento': ['Barras'],
        'dificultad': 'principiante',
        'contraindicaciones': ['cuello'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Zancada con barra',
        'patron_movimiento': 'sentadilla',
        'musculos_primarios': ['cuádriceps', 'glúteos'],
        'musculos_secundarios': ['isquiotibiales', 'lumbar'],
        'equipamiento': ['Barras'],
        'dificultad': 'intermedio',
        'contraindicaciones': ['rodilla', 'lumbar'],
        'bilateral': False,
        'es_compuesto': True,
    },
    # ── MANCUERNAS ─────────────────────────────────────────────────────────────
    {
        'nombre': 'Press de banca con mancuernas',
        'patron_movimiento': 'empuje_horizontal',
        'musculos_primarios': ['pectoral', 'tríceps'],
        'musculos_secundarios': ['hombro anterior'],
        'equipamiento': ['Mancuernas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['hombro'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Press inclinado con mancuernas',
        'patron_movimiento': 'empuje_horizontal',
        'musculos_primarios': ['pectoral superior', 'tríceps'],
        'musculos_secundarios': ['hombro anterior'],
        'equipamiento': ['Mancuernas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['hombro'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Aperturas con mancuernas',
        'patron_movimiento': 'empuje_horizontal',
        'musculos_primarios': ['pectoral'],
        'musculos_secundarios': ['hombro anterior'],
        'equipamiento': ['Mancuernas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['hombro'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Press militar con mancuernas',
        'patron_movimiento': 'empuje_vertical',
        'musculos_primarios': ['deltoides', 'tríceps'],
        'musculos_secundarios': ['core'],
        'equipamiento': ['Mancuernas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['hombro'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Elevación lateral con mancuernas',
        'patron_movimiento': 'empuje_vertical',
        'musculos_primarios': ['deltoides lateral'],
        'musculos_secundarios': [],
        'equipamiento': ['Mancuernas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['hombro', 'codo'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Elevación frontal con mancuernas',
        'patron_movimiento': 'empuje_vertical',
        'musculos_primarios': ['deltoides anterior'],
        'musculos_secundarios': [],
        'equipamiento': ['Mancuernas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['hombro'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Remo con mancuerna a una mano',
        'patron_movimiento': 'jale_horizontal',
        'musculos_primarios': ['dorsal', 'bíceps'],
        'musculos_secundarios': ['romboides', 'lumbar'],
        'equipamiento': ['Mancuernas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['lumbar'],
        'bilateral': False,
        'es_compuesto': True,
    },
    {
        'nombre': 'Remo inclinado con mancuernas',
        'patron_movimiento': 'jale_horizontal',
        'musculos_primarios': ['dorsal', 'bíceps', 'romboides'],
        'musculos_secundarios': ['lumbar'],
        'equipamiento': ['Mancuernas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['lumbar'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Pullover con mancuerna',
        'patron_movimiento': 'jale_vertical',
        'musculos_primarios': ['dorsal', 'pectoral'],
        'musculos_secundarios': ['tríceps'],
        'equipamiento': ['Mancuernas'],
        'dificultad': 'intermedio',
        'contraindicaciones': ['hombro', 'lumbar'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Curl de bíceps con mancuernas',
        'patron_movimiento': 'jale_vertical',
        'musculos_primarios': ['bíceps'],
        'musculos_secundarios': ['braquial'],
        'equipamiento': ['Mancuernas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['codo'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Curl martillo',
        'patron_movimiento': 'jale_vertical',
        'musculos_primarios': ['bíceps', 'braquial'],
        'musculos_secundarios': ['braquioradial'],
        'equipamiento': ['Mancuernas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['codo'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Curl de concentración',
        'patron_movimiento': 'jale_vertical',
        'musculos_primarios': ['bíceps'],
        'musculos_secundarios': [],
        'equipamiento': ['Mancuernas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['codo'],
        'bilateral': False,
        'es_compuesto': False,
    },
    {
        'nombre': 'Extensión de tríceps sobre la cabeza',
        'patron_movimiento': 'empuje_vertical',
        'musculos_primarios': ['tríceps'],
        'musculos_secundarios': [],
        'equipamiento': ['Mancuernas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['codo', 'hombro'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Patada de tríceps con mancuerna',
        'patron_movimiento': 'empuje_horizontal',
        'musculos_primarios': ['tríceps'],
        'musculos_secundarios': [],
        'equipamiento': ['Mancuernas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['codo'],
        'bilateral': False,
        'es_compuesto': False,
    },
    {
        'nombre': 'Sentadilla goblet con mancuerna',
        'patron_movimiento': 'sentadilla',
        'musculos_primarios': ['cuádriceps', 'glúteos'],
        'musculos_secundarios': ['core', 'isquiotibiales'],
        'equipamiento': ['Mancuernas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['rodilla'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Peso muerto rumano con mancuernas',
        'patron_movimiento': 'bisagra',
        'musculos_primarios': ['isquiotibiales', 'glúteos'],
        'musculos_secundarios': ['lumbar'],
        'equipamiento': ['Mancuernas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['lumbar'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Peso muerto sumo con mancuernas',
        'patron_movimiento': 'bisagra',
        'musculos_primarios': ['isquiotibiales', 'glúteos', 'aductores'],
        'musculos_secundarios': ['lumbar'],
        'equipamiento': ['Mancuernas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['lumbar', 'cadera'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Zancada con mancuernas',
        'patron_movimiento': 'sentadilla',
        'musculos_primarios': ['cuádriceps', 'glúteos'],
        'musculos_secundarios': ['isquiotibiales'],
        'equipamiento': ['Mancuernas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['rodilla'],
        'bilateral': False,
        'es_compuesto': True,
    },
    {
        'nombre': 'Sentadilla búlgara con mancuernas',
        'patron_movimiento': 'sentadilla',
        'musculos_primarios': ['cuádriceps', 'glúteos'],
        'musculos_secundarios': ['isquiotibiales'],
        'equipamiento': ['Mancuernas'],
        'dificultad': 'intermedio',
        'contraindicaciones': ['rodilla', 'cadera'],
        'bilateral': False,
        'es_compuesto': True,
    },
    {
        'nombre': 'Step-up con mancuernas',
        'patron_movimiento': 'sentadilla',
        'musculos_primarios': ['cuádriceps', 'glúteos'],
        'musculos_secundarios': ['isquiotibiales'],
        'equipamiento': ['Mancuernas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['rodilla'],
        'bilateral': False,
        'es_compuesto': True,
    },
    {
        'nombre': 'Hip thrust con mancuerna',
        'patron_movimiento': 'bisagra',
        'musculos_primarios': ['glúteos'],
        'musculos_secundarios': ['isquiotibiales', 'core'],
        'equipamiento': ['Mancuernas'],
        'dificultad': 'principiante',
        'contraindicaciones': [],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Encogimientos con mancuernas',
        'patron_movimiento': 'jale_vertical',
        'musculos_primarios': ['trapecios'],
        'musculos_secundarios': [],
        'equipamiento': ['Mancuernas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['cuello'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Aperturas inversas con mancuernas',
        'patron_movimiento': 'jale_horizontal',
        'musculos_primarios': ['deltoides posterior', 'romboides'],
        'musculos_secundarios': [],
        'equipamiento': ['Mancuernas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['hombro'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Elevación de talones con mancuernas',
        'patron_movimiento': 'cardio',
        'musculos_primarios': ['pantorrilla'],
        'musculos_secundarios': ['sóleo'],
        'equipamiento': ['Mancuernas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['tobillo'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Peso muerto con mancuernas',
        'patron_movimiento': 'bisagra',
        'musculos_primarios': ['isquiotibiales', 'glúteos', 'lumbar'],
        'musculos_secundarios': ['trapecios'],
        'equipamiento': ['Mancuernas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['lumbar'],
        'bilateral': True,
        'es_compuesto': True,
    },
    # ── MÁQUINAS ───────────────────────────────────────────────────────────────
    {
        'nombre': 'Jalón al pecho',
        'patron_movimiento': 'jale_vertical',
        'musculos_primarios': ['dorsal', 'bíceps'],
        'musculos_secundarios': ['romboides'],
        'equipamiento': ['Máquinas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['hombro'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Remo en polea baja',
        'patron_movimiento': 'jale_horizontal',
        'musculos_primarios': ['dorsal', 'bíceps', 'romboides'],
        'musculos_secundarios': ['lumbar'],
        'equipamiento': ['Máquinas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['lumbar'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Face pull en polea',
        'patron_movimiento': 'jale_horizontal',
        'musculos_primarios': ['deltoides posterior', 'manguito rotador'],
        'musculos_secundarios': ['romboides'],
        'equipamiento': ['Máquinas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['hombro'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Elevación lateral en polea',
        'patron_movimiento': 'empuje_vertical',
        'musculos_primarios': ['deltoides lateral'],
        'musculos_secundarios': [],
        'equipamiento': ['Máquinas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['hombro'],
        'bilateral': False,
        'es_compuesto': False,
    },
    {
        'nombre': 'Cruce de poleas alto',
        'patron_movimiento': 'empuje_horizontal',
        'musculos_primarios': ['pectoral inferior'],
        'musculos_secundarios': ['hombro anterior'],
        'equipamiento': ['Máquinas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['hombro'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Cruce de poleas bajo',
        'patron_movimiento': 'empuje_horizontal',
        'musculos_primarios': ['pectoral superior'],
        'musculos_secundarios': ['hombro anterior'],
        'equipamiento': ['Máquinas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['hombro'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Extensión de tríceps en polea',
        'patron_movimiento': 'empuje_horizontal',
        'musculos_primarios': ['tríceps'],
        'musculos_secundarios': [],
        'equipamiento': ['Máquinas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['codo'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Curl de bíceps en polea',
        'patron_movimiento': 'jale_vertical',
        'musculos_primarios': ['bíceps'],
        'musculos_secundarios': ['braquial'],
        'equipamiento': ['Máquinas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['codo'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Pull-through en polea',
        'patron_movimiento': 'bisagra',
        'musculos_primarios': ['glúteos', 'isquiotibiales'],
        'musculos_secundarios': ['lumbar'],
        'equipamiento': ['Máquinas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['lumbar'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Crunch en polea',
        'patron_movimiento': 'core',
        'musculos_primarios': ['recto abdominal'],
        'musculos_secundarios': ['oblicuos'],
        'equipamiento': ['Máquinas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['lumbar', 'cuello'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Woodchop en polea',
        'patron_movimiento': 'core',
        'musculos_primarios': ['oblicuos', 'core'],
        'musculos_secundarios': ['hombro'],
        'equipamiento': ['Máquinas'],
        'dificultad': 'intermedio',
        'contraindicaciones': ['lumbar'],
        'bilateral': False,
        'es_compuesto': False,
    },
    {
        'nombre': 'Prensa de piernas',
        'patron_movimiento': 'sentadilla',
        'musculos_primarios': ['cuádriceps', 'glúteos'],
        'musculos_secundarios': ['isquiotibiales'],
        'equipamiento': ['Máquinas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['rodilla'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Extensión de cuádriceps',
        'patron_movimiento': 'sentadilla',
        'musculos_primarios': ['cuádriceps'],
        'musculos_secundarios': [],
        'equipamiento': ['Máquinas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['rodilla'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Curl de isquiotibiales tumbado',
        'patron_movimiento': 'bisagra',
        'musculos_primarios': ['isquiotibiales'],
        'musculos_secundarios': [],
        'equipamiento': ['Máquinas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['rodilla'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Curl de isquiotibiales sentado',
        'patron_movimiento': 'bisagra',
        'musculos_primarios': ['isquiotibiales'],
        'musculos_secundarios': [],
        'equipamiento': ['Máquinas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['rodilla'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Abducción de cadera en máquina',
        'patron_movimiento': 'sentadilla',
        'musculos_primarios': ['abductores', 'TFL'],
        'musculos_secundarios': [],
        'equipamiento': ['Máquinas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['cadera'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Aducción de cadera en máquina',
        'patron_movimiento': 'sentadilla',
        'musculos_primarios': ['aductores'],
        'musculos_secundarios': [],
        'equipamiento': ['Máquinas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['cadera'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Press de pecho en máquina',
        'patron_movimiento': 'empuje_horizontal',
        'musculos_primarios': ['pectoral', 'tríceps'],
        'musculos_secundarios': ['hombro anterior'],
        'equipamiento': ['Máquinas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['hombro'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Press de hombros en máquina',
        'patron_movimiento': 'empuje_vertical',
        'musculos_primarios': ['deltoides', 'tríceps'],
        'musculos_secundarios': [],
        'equipamiento': ['Máquinas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['hombro'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Pec deck mariposa',
        'patron_movimiento': 'empuje_horizontal',
        'musculos_primarios': ['pectoral'],
        'musculos_secundarios': ['hombro anterior'],
        'equipamiento': ['Máquinas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['hombro'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Aperturas inversas en máquina',
        'patron_movimiento': 'jale_horizontal',
        'musculos_primarios': ['deltoides posterior', 'romboides'],
        'musculos_secundarios': [],
        'equipamiento': ['Máquinas'],
        'dificultad': 'principiante',
        'contraindicaciones': [],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Patada de glúteos en polea',
        'patron_movimiento': 'bisagra',
        'musculos_primarios': ['glúteos'],
        'musculos_secundarios': ['isquiotibiales'],
        'equipamiento': ['Máquinas'],
        'dificultad': 'principiante',
        'contraindicaciones': [],
        'bilateral': False,
        'es_compuesto': False,
    },
    {
        'nombre': 'Elevación de talones en máquina',
        'patron_movimiento': 'cardio',
        'musculos_primarios': ['pantorrilla', 'sóleo'],
        'musculos_secundarios': [],
        'equipamiento': ['Máquinas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['tobillo'],
        'bilateral': True,
        'es_compuesto': False,
    },
    # ── KETTLEBELLS ────────────────────────────────────────────────────────────
    {
        'nombre': 'Swing con kettlebell',
        'patron_movimiento': 'bisagra',
        'musculos_primarios': ['glúteos', 'isquiotibiales', 'core'],
        'musculos_secundarios': ['lumbar', 'hombro'],
        'equipamiento': ['Kettlebells'],
        'dificultad': 'intermedio',
        'contraindicaciones': ['lumbar'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Sentadilla goblet con kettlebell',
        'patron_movimiento': 'sentadilla',
        'musculos_primarios': ['cuádriceps', 'glúteos'],
        'musculos_secundarios': ['core'],
        'equipamiento': ['Kettlebells'],
        'dificultad': 'principiante',
        'contraindicaciones': ['rodilla'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Peso muerto con kettlebell',
        'patron_movimiento': 'bisagra',
        'musculos_primarios': ['isquiotibiales', 'glúteos'],
        'musculos_secundarios': ['lumbar'],
        'equipamiento': ['Kettlebells'],
        'dificultad': 'principiante',
        'contraindicaciones': ['lumbar'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Press militar con kettlebell',
        'patron_movimiento': 'empuje_vertical',
        'musculos_primarios': ['deltoides', 'tríceps'],
        'musculos_secundarios': ['core'],
        'equipamiento': ['Kettlebells'],
        'dificultad': 'intermedio',
        'contraindicaciones': ['hombro', 'muñeca'],
        'bilateral': False,
        'es_compuesto': True,
    },
    {
        'nombre': 'Remo con kettlebell',
        'patron_movimiento': 'jale_horizontal',
        'musculos_primarios': ['dorsal', 'bíceps'],
        'musculos_secundarios': ['lumbar'],
        'equipamiento': ['Kettlebells'],
        'dificultad': 'principiante',
        'contraindicaciones': ['lumbar'],
        'bilateral': False,
        'es_compuesto': True,
    },
    {
        'nombre': 'Turkish get-up',
        'patron_movimiento': 'movilidad',
        'musculos_primarios': ['cuerpo completo', 'core'],
        'musculos_secundarios': ['hombro'],
        'equipamiento': ['Kettlebells'],
        'dificultad': 'avanzado',
        'contraindicaciones': ['hombro', 'muñeca'],
        'bilateral': False,
        'es_compuesto': True,
    },
    {
        'nombre': 'Snatch con kettlebell',
        'patron_movimiento': 'cardio',
        'musculos_primarios': ['cuerpo completo'],
        'musculos_secundarios': ['hombro', 'core'],
        'equipamiento': ['Kettlebells'],
        'dificultad': 'avanzado',
        'contraindicaciones': ['hombro', 'muñeca', 'lumbar'],
        'bilateral': False,
        'es_compuesto': True,
    },
    # ── BANDAS ELÁSTICAS ───────────────────────────────────────────────────────
    {
        'nombre': 'Separación de bandas',
        'patron_movimiento': 'jale_horizontal',
        'musculos_primarios': ['deltoides posterior', 'romboides'],
        'musculos_secundarios': [],
        'equipamiento': ['Bandas elásticas'],
        'dificultad': 'principiante',
        'contraindicaciones': [],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Face pull con banda',
        'patron_movimiento': 'jale_horizontal',
        'musculos_primarios': ['deltoides posterior', 'manguito rotador'],
        'musculos_secundarios': [],
        'equipamiento': ['Bandas elásticas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['hombro'],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Elevación lateral con banda',
        'patron_movimiento': 'empuje_vertical',
        'musculos_primarios': ['deltoides lateral'],
        'musculos_secundarios': [],
        'equipamiento': ['Bandas elásticas'],
        'dificultad': 'principiante',
        'contraindicaciones': [],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Sentadilla con banda',
        'patron_movimiento': 'sentadilla',
        'musculos_primarios': ['cuádriceps', 'glúteos'],
        'musculos_secundarios': ['isquiotibiales'],
        'equipamiento': ['Bandas elásticas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['rodilla'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Peso muerto con banda',
        'patron_movimiento': 'bisagra',
        'musculos_primarios': ['isquiotibiales', 'glúteos'],
        'musculos_secundarios': ['lumbar'],
        'equipamiento': ['Bandas elásticas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['lumbar'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Curl de bíceps con banda',
        'patron_movimiento': 'jale_vertical',
        'musculos_primarios': ['bíceps'],
        'musculos_secundarios': [],
        'equipamiento': ['Bandas elásticas'],
        'dificultad': 'principiante',
        'contraindicaciones': [],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Extensión de tríceps con banda',
        'patron_movimiento': 'empuje_vertical',
        'musculos_primarios': ['tríceps'],
        'musculos_secundarios': [],
        'equipamiento': ['Bandas elásticas'],
        'dificultad': 'principiante',
        'contraindicaciones': [],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Patada de glúteos con banda',
        'patron_movimiento': 'bisagra',
        'musculos_primarios': ['glúteos'],
        'musculos_secundarios': ['isquiotibiales'],
        'equipamiento': ['Bandas elásticas'],
        'dificultad': 'principiante',
        'contraindicaciones': [],
        'bilateral': False,
        'es_compuesto': False,
    },
    {
        'nombre': 'Caminata lateral con banda',
        'patron_movimiento': 'sentadilla',
        'musculos_primarios': ['abductores', 'glúteos'],
        'musculos_secundarios': [],
        'equipamiento': ['Bandas elásticas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['rodilla'],
        'bilateral': False,
        'es_compuesto': False,
    },
    {
        'nombre': 'Press de banca con banda',
        'patron_movimiento': 'empuje_horizontal',
        'musculos_primarios': ['pectoral', 'tríceps'],
        'musculos_secundarios': ['hombro'],
        'equipamiento': ['Bandas elásticas'],
        'dificultad': 'principiante',
        'contraindicaciones': ['hombro'],
        'bilateral': True,
        'es_compuesto': True,
    },
    # ── TRX ────────────────────────────────────────────────────────────────────
    {
        'nombre': 'Remo en TRX',
        'patron_movimiento': 'jale_horizontal',
        'musculos_primarios': ['dorsal', 'bíceps', 'romboides'],
        'musculos_secundarios': ['core'],
        'equipamiento': ['TRX'],
        'dificultad': 'principiante',
        'contraindicaciones': ['hombro'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Curl de bíceps en TRX',
        'patron_movimiento': 'jale_vertical',
        'musculos_primarios': ['bíceps'],
        'musculos_secundarios': ['core'],
        'equipamiento': ['TRX'],
        'dificultad': 'principiante',
        'contraindicaciones': [],
        'bilateral': True,
        'es_compuesto': False,
    },
    {
        'nombre': 'Press en TRX',
        'patron_movimiento': 'empuje_horizontal',
        'musculos_primarios': ['pectoral', 'tríceps'],
        'musculos_secundarios': ['core', 'hombro'],
        'equipamiento': ['TRX'],
        'dificultad': 'intermedio',
        'contraindicaciones': ['hombro', 'muñeca'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Sentadilla con TRX',
        'patron_movimiento': 'sentadilla',
        'musculos_primarios': ['cuádriceps', 'glúteos'],
        'musculos_secundarios': ['core'],
        'equipamiento': ['TRX'],
        'dificultad': 'principiante',
        'contraindicaciones': ['rodilla'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Zancada con TRX',
        'patron_movimiento': 'sentadilla',
        'musculos_primarios': ['cuádriceps', 'glúteos'],
        'musculos_secundarios': ['core'],
        'equipamiento': ['TRX'],
        'dificultad': 'intermedio',
        'contraindicaciones': ['rodilla'],
        'bilateral': False,
        'es_compuesto': True,
    },
    {
        'nombre': 'Plancha con TRX',
        'patron_movimiento': 'core',
        'musculos_primarios': ['core', 'hombro'],
        'musculos_secundarios': ['glúteos'],
        'equipamiento': ['TRX'],
        'dificultad': 'intermedio',
        'contraindicaciones': ['hombro', 'muñeca', 'lumbar'],
        'bilateral': True,
        'es_compuesto': False,
    },
    # ── CAJÓN PLIOMÉTRICO ──────────────────────────────────────────────────────
    {
        'nombre': 'Salto al cajón',
        'patron_movimiento': 'cardio',
        'musculos_primarios': ['cuádriceps', 'glúteos'],
        'musculos_secundarios': ['isquiotibiales', 'pantorrilla'],
        'equipamiento': ['Cajón pliométrico'],
        'dificultad': 'intermedio',
        'contraindicaciones': ['rodilla', 'tobillo'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Step-up con cajón',
        'patron_movimiento': 'sentadilla',
        'musculos_primarios': ['cuádriceps', 'glúteos'],
        'musculos_secundarios': ['isquiotibiales'],
        'equipamiento': ['Cajón pliométrico'],
        'dificultad': 'principiante',
        'contraindicaciones': ['rodilla'],
        'bilateral': False,
        'es_compuesto': True,
    },
    {
        'nombre': 'Salto desde cajón',
        'patron_movimiento': 'cardio',
        'musculos_primarios': ['cuádriceps', 'glúteos'],
        'musculos_secundarios': ['pantorrilla', 'core'],
        'equipamiento': ['Cajón pliométrico'],
        'dificultad': 'intermedio',
        'contraindicaciones': ['rodilla', 'tobillo'],
        'bilateral': True,
        'es_compuesto': True,
    },
    # ── ANILLAS ────────────────────────────────────────────────────────────────
    {
        'nombre': 'Fondos en anillas',
        'patron_movimiento': 'empuje_horizontal',
        'musculos_primarios': ['pectoral', 'tríceps'],
        'musculos_secundarios': ['hombro', 'core'],
        'equipamiento': ['Anillas'],
        'dificultad': 'avanzado',
        'contraindicaciones': ['hombro', 'codo', 'muñeca'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Remo en anillas',
        'patron_movimiento': 'jale_horizontal',
        'musculos_primarios': ['dorsal', 'bíceps', 'romboides'],
        'musculos_secundarios': ['core'],
        'equipamiento': ['Anillas'],
        'dificultad': 'intermedio',
        'contraindicaciones': ['hombro'],
        'bilateral': True,
        'es_compuesto': True,
    },
    {
        'nombre': 'Curl de bíceps en anillas',
        'patron_movimiento': 'jale_vertical',
        'musculos_primarios': ['bíceps'],
        'musculos_secundarios': ['core'],
        'equipamiento': ['Anillas'],
        'dificultad': 'intermedio',
        'contraindicaciones': ['codo'],
        'bilateral': True,
        'es_compuesto': False,
    },
]


class Command(BaseCommand):
    help = '[DEPRECATED] Use the SQL files in backend/sql/ instead. Run zyfit_exercise_schema.sql then the 5 seed batch files.'

    def handle(self, *args, **options):
        raise CommandError(
            'This command is deprecated. The exercise catalog has been replaced by the normalized SQL schema.\n'
            'To seed exercises, run these SQL files against your PostgreSQL database in order:\n'
            '  1. backend/sql/zyfit_exercise_schema.sql\n'
            '  2. backend/sql/zyfit_seed_exercises_01_bisagra_sentadilla.sql\n'
            '  3. backend/sql/zyfit_seed_exercises_02_empuje.sql\n'
            '  4. backend/sql/zyfit_seed_exercises_03_jalon.sql\n'
            '  5. backend/sql/zyfit_seed_exercises_04_core.sql\n'
            '  6. backend/sql/zyfit_seed_exercises_05_aislamiento.sql\n'
        )
        created_count = 0
        updated_count = 0

        for data in EXERCISES:
            obj, created = Exercise.objects.update_or_create(
                nombre=data['nombre'],
                defaults={
                    'patron_movimiento': data['patron_movimiento'],
                    'musculos_primarios': data['musculos_primarios'],
                    'musculos_secundarios': data['musculos_secundarios'],
                    'equipamiento': data['equipamiento'],
                    'dificultad': data['dificultad'],
                    'contraindicaciones': data['contraindicaciones'],
                    'bilateral': data['bilateral'],
                    'es_compuesto': data['es_compuesto'],
                    'activo': True,
                },
            )
            if created:
                created_count += 1
            else:
                updated_count += 1

        total = Exercise.objects.count()
        self.stdout.write(
            self.style.SUCCESS(
                f'Done: {created_count} created, {updated_count} updated. '
                f'Total exercises in DB: {total}'
            )
        )
