# Generated by Django 6.0.5 on 2026-07-03 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0007_academystreak_academyactivityday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academy.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_tutor_conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TutorDailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_daily_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academy_tutor_daily_usage',
            },
        ),
        migrations.CreateModel(
            name='TutorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Tutor')], max_length=12)),
                ('contenido', models.TextField()),
                ('fuentes', models.JSONField(blank=True, default=list)),
                ('redirigido', models.BooleanField(default=False)),
                ('feedback', models.CharField(blank=True, choices=[('', 'Sin feedback'), ('util', 'Útil'), ('no_util', 'No útil')], default='', max_length=8)),
                ('tokens_in', models.PositiveIntegerField(blank=True, null=True)),
                ('tokens_out', models.PositiveIntegerField(blank=True, null=True)),
                ('generacion_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('modelo', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='ai_tutor.tutorconversation')),
            ],
            options={
                'db_table': 'academy_tutor_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TutorChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escuela_nombre', models.CharField(blank=True, max_length=160)),
                ('escuela_slug', models.SlugField(blank=True, max_length=90)),
                ('curso_titulo', models.CharField(max_length=180)),
                ('curso_slug', models.SlugField(max_length=90)),
                ('modulo_titulo', models.CharField(blank=True, max_length=160)),
                ('modulo_orden', models.PositiveIntegerField(default=0)),
                ('leccion_titulo', models.CharField(max_length=180)),
                ('leccion_orden', models.PositiveIntegerField(default=0)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('contenido', models.TextField()),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('embedding_model', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_chunks', to='academy.course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_chunks', to='academy.lesson')),
            ],
            options={
                'db_table': 'academy_tutor_chunks',
                'ordering': ['course', 'modulo_orden', 'leccion_orden', 'chunk_index'],
                'indexes': [models.Index(fields=['course', 'chunk_index'], name='academy_tut_course__2ee9ee_idx')],
                'unique_together': {('lesson', 'chunk_index')},
            },
        ),
        migrations.AddIndex(
            model_name='tutorconversation',
            index=models.Index(fields=['user', '-updated_at'], name='academy_tut_user_id_fbd423_idx'),
        ),
        migrations.AddIndex(
            model_name='tutordailyusage',
            index=models.Index(fields=['user', 'fecha'], name='academy_tut_user_id_2f37d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tutordailyusage',
            unique_together={('user', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='tutormessage',
            index=models.Index(fields=['conversation', 'created_at'], name='academy_tut_convers_e3a8fe_idx'),
        ),
    ]
