# Generated by Django 6.0.5 on 2026-05-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado_animo', models.IntegerField()),
                ('calidad_sueno', models.DecimalField(decimal_places=1, max_digits=4)),
                ('hrv', models.IntegerField(blank=True, null=True)),
                ('duracion_disponible', models.IntegerField()),
                ('foco_entrenamiento', models.JSONField(blank=True, default=list)),
                ('dolor_hoy', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'daily_checkin',
            },
        ),
    ]
