# Generated by Django 6.0.5 on 2026-05-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycheckin',
            name='dolor_hoy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailycheckin',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
