# Generated by Django 6.0.5 on 2026-05-15 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0003_nullable_dolor_hoy_notas'),
        ('users', '0002_userinjury'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailycheckin',
            index=models.Index(fields=['user', '-fecha'], name='daily_check_user_id_968392_idx'),
        ),
    ]
