# Generated by Django 5.2.15 on 2026-07-05 00:29

import devices.fields
from django.db import migrations


def encrypt_existing_dolor_hoy(apps, schema_editor):
    """Re-encripta el dolor_hoy de check-ins ya existentes (guardados en texto
    plano antes de este cambio). Leer una fila ya migrada simplemente falla a
    desencriptar (texto no-Fernet) y devuelve el valor tal cual — guardarla de
    nuevo la encripta con la clave FIELD_ENCRYPTION_KEY actual."""
    DailyCheckin = apps.get_model("checkins", "DailyCheckin")
    batch = []
    for c in DailyCheckin.objects.all().iterator():
        batch.append(c)
        if len(batch) >= 500:
            DailyCheckin.objects.bulk_update(batch, ["dolor_hoy"])
            batch = []
    if batch:
        DailyCheckin.objects.bulk_update(batch, ["dolor_hoy"])


class Migration(migrations.Migration):

    dependencies = [
        ("checkins", "0008_dailycheckin_unique_together_user_fecha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailycheckin",
            name="dolor_hoy",
            field=devices.fields.EncryptedTextField(blank=True, null=True),
        ),
        # Sin FIELD_ENCRYPTION_KEY configurada, esto es un no-op silencioso
        # (EncryptedTextField degrada a texto plano — ver devices/fields.py).
        migrations.RunPython(encrypt_existing_dolor_hoy, reverse_code=migrations.RunPython.noop),
    ]
