# Generated by Django 6.0.5 on 2026-08-31 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0008_dailycheckin_unique_together_user_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycheckin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
