# Generated by Django 6.0.5 on 2026-06-05 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('ciudad', models.CharField(blank=True, max_length=120)),
                ('pais', models.CharField(blank=True, max_length=80)),
                ('disciplina', models.CharField(blank=True, help_text='Deporte principal del centro (fútbol, atletismo, natación…).', max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('director_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros_dirigidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'performance_centers',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PsychAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('estado_animo', 'Estado de ánimo'), ('ansiedad', 'Ansiedad'), ('motivacion', 'Motivación'), ('estres', 'Estrés'), ('cohesion', 'Cohesión de equipo'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('puntuacion', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='performance.sportscenter')),
            ],
            options={
                'db_table': 'performance_psych_assessments',
                'ordering': ['-fecha', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['center', 'athlete', '-fecha'], name='performance_center__5f7112_idx')],
            },
        ),
        migrations.CreateModel(
            name='PhysicalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=120)),
                ('categoria', models.CharField(blank=True, max_length=80)),
                ('resultado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(blank=True, max_length=20)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='performance.sportscenter')),
            ],
            options={
                'db_table': 'performance_tests',
                'ordering': ['-fecha', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['center', 'athlete', '-fecha'], name='performance_center__264b50_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('velocidad', 'Velocidad'), ('fuerza', 'Fuerza'), ('potencia', 'Potencia'), ('resistencia', 'Resistencia'), ('carga', 'Carga de trabajo'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('metrica', models.CharField(max_length=120)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(blank=True, max_length=20)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='performance.sportscenter')),
            ],
            options={
                'db_table': 'performance_metrics',
                'ordering': ['-fecha', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['center', 'athlete', '-fecha'], name='performance_center__0cdff7_idx')],
            },
        ),
        migrations.CreateModel(
            name='InjuryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zona', models.CharField(max_length=80)),
                ('diagnostico', models.CharField(blank=True, max_length=200)),
                ('severidad', models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('grave', 'Grave')], default='leve', max_length=20)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('recuperacion', 'En recuperación'), ('alta', 'Alta')], default='activa', max_length=20)),
                ('tratamiento', models.TextField(blank=True)),
                ('fecha_alta_estimada', models.DateField(blank=True, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='performance.sportscenter')),
            ],
            options={
                'db_table': 'performance_injury_reports',
                'ordering': ['-fecha', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['center', 'estado'], name='performance_center__b779a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='CenterMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('director_tecnico', 'Director técnico'), ('preparador_fisico', 'Preparador físico'), ('fisioterapeuta', 'Fisioterapeuta'), ('analista', 'Analista de test'), ('planificador', 'Planificador'), ('psicologo', 'Psicólogo')], max_length=30)),
                ('modulos', models.JSONField(blank=True, default=list)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_memberships', to=settings.AUTH_USER_MODEL)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='performance.sportscenter')),
            ],
            options={
                'db_table': 'performance_memberships',
                'ordering': ['center', 'rol'],
                'indexes': [models.Index(fields=['center', 'activo'], name='performance_center__f2e1f3_idx')],
                'unique_together': {('center', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CenterAthlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorsal', models.CharField(blank=True, max_length=10)),
                ('posicion', models.CharField(blank=True, max_length=80)),
                ('grupo', models.CharField(blank=True, help_text='Subgrupo / categoría dentro del centro (sub-18, primer equipo…).', max_length=80)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('lesionado', 'Lesionado'), ('baja', 'Baja')], default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_athlete_links', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atletas_registrados', to=settings.AUTH_USER_MODEL)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atletas', to='performance.sportscenter')),
            ],
            options={
                'db_table': 'performance_center_athletes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['center', 'estado'], name='performance_center__f748aa_idx')],
                'unique_together': {('center', 'athlete')},
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('objetivo', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='performance.sportscenter')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'performance_plans',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['center', '-fecha_inicio'], name='performance_center__5041a9_idx')],
            },
        ),
    ]
