# Generated by Django 6.0.5 on 2026-06-06 02:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('familia', models.CharField(choices=[('fisico', 'Físico'), ('tecnico', 'Técnico'), ('tactico', 'Táctico')], max_length=20)),
                ('nombre', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True)),
                ('input_schema', models.JSONField(blank=True, default=list)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'performance_test_definitions',
                'ordering': ['familia', 'slug'],
            },
        ),
        migrations.AddField(
            model_name='physicaltest',
            name='inputs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='physicaltest',
            name='resultados',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='physicaltest',
            name='test_slug',
            field=models.SlugField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='physicaltest',
            name='resultado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddIndex(
            model_name='physicaltest',
            index=models.Index(fields=['center', 'test_slug', '-fecha'], name='performance_center__91d320_idx'),
        ),
    ]
