# Generated by Django 6.0.5 on 2026-06-06 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_testdefinition_physicaltest_inputs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesocycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('prep_general', 'Preparación general'), ('prep_especifica', 'Preparación específica'), ('precompetitivo', 'Precompetitivo'), ('competitivo', 'Competitivo'), ('transicion', 'Transición')], default='prep_general', max_length=20)),
                ('enfasis', models.CharField(blank=True, max_length=200)),
                ('carga_objetivo', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('pico', 'Pico')], default='media', max_length=10)),
                ('duracion_semanas', models.PositiveIntegerField(default=4)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesociclos', to='performance.trainingplan')),
            ],
            options={
                'db_table': 'performance_mesocycles',
                'ordering': ['plan', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Microcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('tipo', models.CharField(choices=[('ajuste', 'Ajuste'), ('carga', 'Carga'), ('choque', 'Choque'), ('activacion', 'Activación'), ('competitivo', 'Competitivo'), ('recuperacion', 'Recuperación')], default='carga', max_length=20)),
                ('carga_relativa', models.PositiveIntegerField(default=50)),
                ('volumen', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='medio', max_length=10)),
                ('intensidad', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='medio', max_length=10)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mesociclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microciclos', to='performance.mesocycle')),
            ],
            options={
                'db_table': 'performance_microcycles',
                'ordering': ['mesociclo', 'orden'],
            },
        ),
        migrations.AddIndex(
            model_name='mesocycle',
            index=models.Index(fields=['plan', 'orden'], name='performance_plan_id_c65cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='microcycle',
            index=models.Index(fields=['mesociclo', 'orden'], name='performance_mesocic_f8cc7d_idx'),
        ),
    ]
