# Generated by Django 6.0.5 on 2026-06-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_mesocycle_microcycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microcycle',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='grupo',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
