# Generated by Django 6.0.5 on 2026-06-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0005_wellnesscheckin'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychassessment',
            name='instrument',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='psychassessment',
            name='resultados',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='psychassessment',
            name='subescalas',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
