# Generated by Django 6.0.5 on 2026-06-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0006_psychassessment_instrument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centerathlete',
            name='foto',
            field=models.TextField(blank=True, help_text='Foto del atleta como data URL (base64). La imagen se recorta y reescala en el cliente (~256 px JPEG). Es una solución provisional sin almacenamiento de objetos: cuando exista (DO Spaces / S3) se cambia por un ImageField + subida con URL firmada.'),
        ),
    ]
