# Generated by Django 6.0.5 on 2026-06-06 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0007_centerathlete_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TacticalPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('descripcion', models.TextField(blank=True)),
                ('formacion', models.CharField(blank=True, help_text='Formación, p. ej. "4-3-3" (opcional).', max_length=40)),
                ('campo', models.CharField(default='completo', help_text='Vista de cancha: completo | medio (para futuros set pieces).', max_length=20)),
                ('escena', models.JSONField(blank=True, default=dict, help_text='Documento de la escena con coordenadas normalizadas (0..1). Ver docstring.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadas', to='performance.sportscenter')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'performance_tactical_plays',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['center', '-updated_at'], name='performance_center__d2aeb4_idx')],
            },
        ),
    ]
