# Generated by Django 6.0.5 on 2026-06-07 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0008_tacticalplay'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('temporada', 'Temporada'), ('torneo', 'Torneo'), ('concentracion', 'Concentración'), ('partido', 'Partido'), ('entrenamiento', 'Entrenamiento'), ('evaluacion', 'Evaluación'), ('descanso', 'Descanso'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('titulo', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('todo_el_dia', models.BooleanField(default=True)),
                ('ubicacion', models.CharField(blank=True, max_length=160)),
                ('grupo', models.CharField(blank=True, max_length=80)),
                ('rival', models.CharField(blank=True, max_length=120)),
                ('localia', models.CharField(blank=True, choices=[('local', 'Local'), ('visita', 'Visitante'), ('neutral', 'Cancha neutral')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='performance.sportscenter')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'performance_calendar_events',
                'ordering': ['fecha_inicio', 'hora_inicio'],
                'indexes': [models.Index(fields=['center', 'fecha_inicio'], name='performance_center__83f9fb_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='calendarevent_fin_after_inicio')],
            },
        ),
    ]
