# Generated by Django 6.0.5 on 2026-06-09 02:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0009_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='injuryreport',
            name='mecanismo',
            field=models.CharField(blank=True, help_text='Mecanismo lesional (sprint, contacto, sobrecarga, esguince…).', max_length=120),
        ),
        migrations.AddField(
            model_name='injuryreport',
            name='tipo',
            field=models.CharField(choices=[('muscular', 'Muscular'), ('articular', 'Articular'), ('ligamentosa', 'Ligamentosa'), ('tendinosa', 'Tendinosa'), ('osea', 'Ósea')], default='muscular', max_length=20),
        ),
        migrations.AddField(
            model_name='injuryreport',
            name='vista',
            field=models.CharField(choices=[('frente', 'Frente'), ('espalda', 'Espalda')], default='frente', max_length=10),
        ),
        migrations.AddField(
            model_name='injuryreport',
            name='zona_x',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='injuryreport',
            name='zona_y',
            field=models.PositiveSmallIntegerField(default=200, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(415)]),
        ),
    ]
