# Generated by Django 6.0.5 on 2026-06-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0010_injuryreport_mecanismo_injuryreport_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centerathlete',
            name='foto_img',
            field=models.FileField(blank=True, null=True, upload_to='athletes/'),
        ),
        migrations.AlterField(
            model_name='centerathlete',
            name='foto',
            field=models.TextField(blank=True, help_text='Foto del atleta como data URL (base64). Vía LEGADA / fallback: se usa solo cuando DO Spaces no está configurado (USE_SPACES=False). Con Spaces activo, la foto vive en `foto_img` y este campo queda vacío. Se conserva para no perder fotos antiguas en filas ya existentes.'),
        ),
    ]
