# Generated by Django 6.0.5 on 2026-07-06 11:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0011_centerathlete_foto_img_alter_centerathlete_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('fecha', models.DateField(blank=True, null=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('tipo', models.CharField(choices=[('fuerza', 'Fuerza'), ('tecnico_tactico', 'Técnico-táctico'), ('fisico', 'Físico / condicional'), ('recuperacion', 'Recuperación'), ('partido', 'Partido'), ('descanso', 'Descanso'), ('otro', 'Otro')], default='tecnico_tactico', max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=160)),
                ('duracion_min', models.PositiveIntegerField(blank=True, null=True)),
                ('rpe_objetivo', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('carga_objetivo_ua', models.PositiveIntegerField(blank=True, null=True)),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('ia', 'IA')], default='manual', max_length=10)),
                ('contenido', models.JSONField(blank=True, default=dict)),
                ('respuesta_ia', models.JSONField(blank=True, null=True)),
                ('prompt_usado', models.TextField(blank=True)),
                ('generacion_ms', models.IntegerField(blank=True, null=True)),
                ('tokens_in', models.IntegerField(blank=True, null=True)),
                ('tokens_out', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('generada', 'Generada con IA'), ('publicada', 'Publicada')], default='borrador', max_length=12)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_planificadas', to='performance.calendarevent')),
                ('microciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='performance.microcycle')),
            ],
            options={
                'db_table': 'performance_planned_sessions',
                'ordering': ['microciclo', 'dia_semana', 'orden'],
                'indexes': [models.Index(fields=['microciclo', 'dia_semana'], name='performance_microci_41b966_idx'), models.Index(fields=['fecha'], name='performance_fecha_041220_idx')],
            },
        ),
    ]
