# Generated by Django 6.0.5 on 2026-08-13 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0012_plannedsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(blank=True, default='', max_length=2)),
                ('cargo', models.CharField(blank=True, choices=[('preparador_fisico', 'Preparador físico'), ('entrenador', 'Entrenador / DT'), ('analista', 'Analista de rendimiento'), ('coordinador', 'Coordinador de formativas'), ('director_deportivo', 'Director deportivo'), ('dueno', 'Dueño / directivo del club'), ('fisioterapeuta', 'Fisioterapeuta / kinesiólogo'), ('medico', 'Médico deportivo'), ('nutricionista', 'Nutricionista deportivo'), ('psicologo', 'Psicólogo deportivo'), ('atleta', 'Atleta independiente'), ('otro', 'Otro')], max_length=30)),
                ('cargo_otro', models.CharField(blank=True, default='', max_length=80)),
                ('disciplina', models.CharField(blank=True, choices=[('futbol', 'Fútbol'), ('futsal', 'Futsal'), ('basquet', 'Básquetbol'), ('voley', 'Vóleibol'), ('handball', 'Handball'), ('rugby', 'Rugby'), ('atletismo', 'Atletismo'), ('natacion', 'Natación'), ('ciclismo', 'Ciclismo'), ('tenis', 'Tenis'), ('combate', 'Deportes de combate'), ('multideporte', 'Multideporte'), ('otro', 'Otro')], max_length=20)),
                ('disciplina_otro', models.CharField(blank=True, default='', max_length=80)),
                ('tamano_plantel', models.CharField(blank=True, choices=[('solo_1', 'Solo 1 atleta'), ('2_15', '2 a 15 atletas'), ('16_30', '16 a 30 atletas'), ('31_60', '31 a 60 atletas'), ('61_mas', 'Más de 60 atletas')], max_length=10)),
                ('necesidades', models.JSONField(blank=True, default=list)),
                ('canal', models.CharField(blank=True, choices=[('recomendacion', 'Recomendación de un colega'), ('equipo_zyfit', 'Contacto del equipo Zyfit'), ('redes', 'Redes sociales'), ('buscador', 'Búsqueda en internet'), ('evento', 'Congreso, curso o evento'), ('academy', 'Zyfit Academy'), ('prensa', 'Prensa o publicación deportiva'), ('otro', 'Otro')], max_length=20)),
                ('canal_otro', models.CharField(blank=True, default='', max_length=120)),
                ('completado', models.BooleanField(default=False)),
                ('completado_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_onboarding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onboarding de Performance',
                'verbose_name_plural': 'Onboardings de Performance',
                'db_table': 'performance_onboarding',
            },
        ),
    ]
