# Generated by Django 6.0.5 on 2026-08-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0013_performanceonboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceonboarding',
            name='segmento',
            field=models.CharField(blank=True, choices=[('equipos', 'Equipos deportivos'), ('instituciones', 'Instituciones educativas'), ('atletas', 'Atletas de alto rendimiento')], max_length=20),
        ),
        migrations.AlterField(
            model_name='performanceonboarding',
            name='cargo',
            field=models.CharField(blank=True, choices=[('preparador_fisico', 'Preparador físico'), ('entrenador', 'Entrenador / DT'), ('analista', 'Analista de rendimiento'), ('coordinador', 'Coordinador deportivo'), ('director_deportivo', 'Director deportivo'), ('dueno', 'Dueño / directivo del club'), ('fisioterapeuta', 'Fisioterapeuta / kinesiólogo'), ('medico', 'Médico deportivo'), ('nutricionista', 'Nutricionista deportivo'), ('psicologo', 'Psicólogo deportivo'), ('atleta', 'Atleta independiente'), ('profesor_ef', 'Profesor de educación física'), ('director_institucion', 'Director de la institución'), ('entrenador_personal', 'Entrenador personal'), ('otro', 'Otro')], max_length=30),
        ),
    ]
