# Generated by Django 6.0.5 on 2026-08-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0015_reabrir_onboarding_sin_segmento'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportscenter',
            name='tipo',
            field=models.CharField(choices=[('equipos', 'Equipos deportivos'), ('instituciones', 'Instituciones educativas'), ('atletas', 'Atletas de alto rendimiento')], default='equipos', max_length=20),
        ),
    ]
