# Generated by Django 6.0.5 on 2026-08-13 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0016_sportscenter_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sportscenter',
            name='proteccion_menores',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='centerathlete',
            name='grupo',
            field=models.CharField(blank=True, help_text='LEGADO: subgrupo como texto libre. Para instituciones educativas usar `categoria` (modelo Categoria), que sí permite comparar entre categorías y seguir al alumno entre temporadas. Se conserva para no perder datos ya cargados; no se migra automáticamente porque el texto libre no es fiable como fuente (la misma categoría escrita de tres formas serían tres filas).', max_length=80),
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('temporada', models.CharField(blank=True, default='', max_length=20)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='performance.sportscenter')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_a_cargo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'performance_categorias',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='centerathlete',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atletas', to='performance.categoria'),
        ),
        migrations.CreateModel(
            name='ConsentimientoTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_nombre', models.CharField(max_length=160)),
                ('tutor_relacion', models.CharField(choices=[('madre', 'Madre'), ('padre', 'Padre'), ('tutor', 'Tutor/a legal'), ('otro', 'Otro')], default='tutor', max_length=20)),
                ('tutor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('alcance', models.JSONField(blank=True, default=list)),
                ('documento_ref', models.CharField(blank=True, default='', max_length=200)),
                ('otorgado_en', models.DateField()),
                ('revocado_en', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='performance.centerathlete')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'performance_consentimientos',
                'ordering': ['-otorgado_en', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['center', 'activa'], name='performance_center__c064d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('center', 'nombre', 'temporada')},
        ),
        migrations.AddIndex(
            model_name='consentimientotutor',
            index=models.Index(fields=['athlete', 'revocado_en'], name='performance_athlete_6bf63b_idx'),
        ),
    ]
