# Generated by Django 6.0.5 on 2026-08-22 17:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workouts', '0028_exercise_evidence_and_goal_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CyclistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fthr_bpm', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(220)])),
                ('ftp_w', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(600)])),
                ('fc_max', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(220)])),
                ('fc_reposo', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(110)])),
                ('fc_max_es_estimada', models.BooleanField(default=True)),
                ('volumen_semanal_base_horas', models.FloatField(blank=True, null=True)),
                ('zonas', models.JSONField(blank=True, default=dict)),
                ('fuente_baseline', models.CharField(choices=[('test_20min', 'Test de 20-30 min declarado'), ('manual', 'Editado a mano'), ('cold_start', 'Sin datos — provisional')], default='cold_start', max_length=20)),
                ('confianza', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='baja', max_length=10)),
                ('fecha_calculo', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cyclist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cyclist_profiles',
            },
        ),
        migrations.CreateModel(
            name='RidePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_tipo', models.CharField(choices=[('fitness_general', 'Fitness general (sin fecha)'), ('gran_fondo', 'Gran fondo'), ('crono', 'Contrarreloj'), ('ruta_competitiva', 'Ruta competitiva'), ('otra', 'Otra')], default='fitness_general', max_length=20)),
                ('meta_distancia_km', models.FloatField(blank=True, null=True)),
                ('meta_fecha', models.DateField(blank=True, null=True)),
                ('fase_actual', models.CharField(choices=[('base', 'Base'), ('build', 'Construcción'), ('peak', 'Pico'), ('taper', 'Taper'), ('recovery', 'Recuperación/Transición')], default='base', max_length=12)),
                ('semana_actual', models.PositiveSmallIntegerField(default=1)),
                ('total_semanas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('horas_objetivo_semana', models.FloatField(default=0)),
                ('dias_semana', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('dias_preferidos', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateField()),
                ('week_start', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride_plans', to='workouts.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ride_plans',
            },
        ),
        migrations.CreateModel(
            name='RideSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=20)),
                ('session_type', models.CharField(choices=[('free', 'Free Ride'), ('planned', 'Planned Ride')], default='free', max_length=20)),
                ('total_distance_m', models.FloatField(default=0)),
                ('total_duration_s', models.IntegerField(default=0)),
                ('avg_power_w', models.IntegerField(blank=True, null=True)),
                ('normalized_power_w', models.IntegerField(blank=True, null=True)),
                ('avg_cadence_rpm', models.IntegerField(blank=True, null=True)),
                ('avg_heart_rate', models.IntegerField(blank=True, null=True)),
                ('calories_burned', models.FloatField(default=0)),
                ('elevation_gain_m', models.FloatField(default=0)),
                ('rpe_real', models.IntegerField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('cumplimiento', models.IntegerField(blank=True, null=True)),
                ('molestias', models.JSONField(blank=True, default=list)),
                ('feedback_notas', models.TextField(blank=True, null=True)),
                ('feedback_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ride_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PlannedRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_sesion', models.CharField(choices=[('easy', 'Easy/Base'), ('long_ride', 'Salida larga'), ('tempo', 'Tempo'), ('sweet_spot', 'Sweet Spot'), ('threshold', 'Umbral (FTP)'), ('vo2max', 'Intervalos VO2máx'), ('anaerobic', 'Capacidad anaeróbica'), ('sprints', 'Sprints'), ('recovery', 'Recuperación'), ('rest', 'Descanso'), ('cross', 'Cross-training')], max_length=12)),
                ('es_calidad', models.BooleanField(default=False)),
                ('zona_principal', models.CharField(blank=True, max_length=4)),
                ('duracion_objetivo_min', models.IntegerField(blank=True, null=True)),
                ('rpe_target', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('estructura_fases', models.JSONField(blank=True, default=dict)),
                ('respuesta_ia', models.JSONField(blank=True, default=dict)),
                ('prompt_usado', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('ajustada', 'Ajustada por readiness'), ('completada', 'Completada'), ('saltada', 'Saltada')], default='planificada', max_length=12)),
                ('readiness_snapshot', models.JSONField(blank=True, default=dict)),
                ('ajuste_aplicado', models.CharField(blank=True, max_length=40)),
                ('generacion_ms', models.IntegerField(blank=True, null=True)),
                ('tokens_in', models.IntegerField(blank=True, null=True)),
                ('tokens_out', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_rides', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cycling.rideplan')),
                ('ride_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_origin', to='cycling.ridesession')),
            ],
            options={
                'db_table': 'planned_rides',
                'ordering': ['fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='rideplan',
            index=models.Index(fields=['user', 'is_active'], name='ride_plans_user_id_605a15_idx'),
        ),
        migrations.AddConstraint(
            model_name='rideplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_active_ride_plan_per_user'),
        ),
        migrations.AddIndex(
            model_name='ridesession',
            index=models.Index(fields=['user', 'status'], name='ride_sessio_user_id_be99d7_idx'),
        ),
        migrations.AddIndex(
            model_name='ridesession',
            index=models.Index(fields=['user', 'session_type'], name='ride_sessio_user_id_dff3f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='ridesession',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='ride_ended_after_started'),
        ),
        migrations.AddConstraint(
            model_name='ridesession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'completed'), _negated=True), ('ended_at__isnull', False), _connector='OR'), name='ride_completed_has_ended_at'),
        ),
        migrations.AddIndex(
            model_name='plannedride',
            index=models.Index(fields=['user', 'fecha'], name='planned_rid_user_id_d2e5d9_idx'),
        ),
        migrations.AddIndex(
            model_name='plannedride',
            index=models.Index(fields=['plan', 'estado'], name='planned_rid_plan_id_39efbf_idx'),
        ),
        migrations.AddConstraint(
            model_name='plannedride',
            constraint=models.UniqueConstraint(fields=('plan', 'fecha'), name='unique_planned_ride_per_plan_day'),
        ),
    ]
