# Generated by Django 6.0.5 on 2026-09-01 19:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


def _clamp_ride_session_ranges(apps, schema_editor):
    """Antes de agregar los CheckConstraint de rango: clampea/anula cualquier
    valor existente fuera de rango para que el AddConstraint no falle sobre
    datos ya en producción que nunca fueron validados a nivel de BD (antes
    solo el serializer los validaba, no el modelo) — mismo patrón que
    runs/migrations/0007_plannedrunsession_narracion_fallback_and_more.py."""
    RideSession = apps.get_model('cycling', 'RideSession')
    RideSession.objects.filter(total_distance_m__lt=0).update(total_distance_m=0)
    RideSession.objects.filter(total_duration_s__lt=0).update(total_duration_s=0)
    RideSession.objects.filter(avg_power_w__lt=0).update(avg_power_w=None)
    RideSession.objects.filter(normalized_power_w__lt=0).update(normalized_power_w=None)
    RideSession.objects.filter(avg_cadence_rpm__lt=0).update(avg_cadence_rpm=None)
    RideSession.objects.filter(calories_burned__lt=0).update(calories_burned=0)
    RideSession.objects.filter(elevation_gain_m__lt=0).update(elevation_gain_m=0)
    RideSession.objects.exclude(
        Q(rpe_real__isnull=True) | Q(rpe_real__gte=1, rpe_real__lte=10)
    ).update(rpe_real=None)
    RideSession.objects.exclude(
        Q(rating__isnull=True) | Q(rating__gte=1, rating__lte=5)
    ).update(rating=None)
    RideSession.objects.exclude(
        Q(cumplimiento__isnull=True) | Q(cumplimiento__gte=0, cumplimiento__lte=100)
    ).update(cumplimiento=None)


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cycling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CyclistTypeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sesion', models.CharField(choices=[('easy', 'Easy/Base'), ('long_ride', 'Salida larga'), ('tempo', 'Tempo'), ('sweet_spot', 'Sweet Spot'), ('threshold', 'Umbral (FTP)'), ('vo2max', 'Intervalos VO2máx'), ('anaerobic', 'Capacidad anaeróbica'), ('sprints', 'Sprints'), ('recovery', 'Recuperación'), ('rest', 'Descanso'), ('cross', 'Cross-training')], max_length=12)),
                ('veces_realizado', models.IntegerField(default=0)),
                ('rpe_promedio_real', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rpe_promedio_target', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cumplimiento_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ultima_vez', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cyclist_type_profiles',
            },
        ),
        migrations.AddField(
            model_name='plannedride',
            name='narracion_fallback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ridesession',
            name='local_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ridesession',
            name='avg_cadence_rpm',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ridesession',
            name='avg_power_w',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ridesession',
            name='calories_burned',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ridesession',
            name='cumplimiento',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='ridesession',
            name='elevation_gain_m',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ridesession',
            name='normalized_power_w',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ridesession',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='ridesession',
            name='rpe_real',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ridesession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='ridesession',
            name='total_distance_m',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ridesession',
            name='total_duration_s',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='ridesession',
            index=models.Index(fields=['user', 'started_at'], name='ride_sessio_user_id_d26209_idx'),
        ),
        # Limpieza defensiva de datos existentes ANTES de los AddConstraint de
        # abajo — sin esto, si producción ya tiene una fila que violaría un
        # constraint nuevo, el AddConstraint falla al aplicar y el deploy
        # entero se cae (entrypoint.sh corre `migrate` bloqueante).
        migrations.RunPython(_clamp_ride_session_ranges, _noop),
        migrations.AddConstraint(
            model_name='ridesession',
            constraint=models.CheckConstraint(condition=models.Q(('total_distance_m__gte', 0)), name='ride_distance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='ridesession',
            constraint=models.CheckConstraint(condition=models.Q(('total_duration_s__gte', 0)), name='ride_duration_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='ridesession',
            constraint=models.CheckConstraint(condition=models.Q(('avg_power_w__isnull', True), ('avg_power_w__gte', 0), _connector='OR'), name='ride_avg_power_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='ridesession',
            constraint=models.CheckConstraint(condition=models.Q(('normalized_power_w__isnull', True), ('normalized_power_w__gte', 0), _connector='OR'), name='ride_normalized_power_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='ridesession',
            constraint=models.CheckConstraint(condition=models.Q(('avg_cadence_rpm__isnull', True), ('avg_cadence_rpm__gte', 0), _connector='OR'), name='ride_cadence_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='ridesession',
            constraint=models.CheckConstraint(condition=models.Q(('calories_burned__gte', 0)), name='ride_calories_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='ridesession',
            constraint=models.CheckConstraint(condition=models.Q(('elevation_gain_m__gte', 0)), name='ride_elevation_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='ridesession',
            constraint=models.CheckConstraint(condition=models.Q(('rpe_real__isnull', True), models.Q(('rpe_real__gte', 1), ('rpe_real__lte', 10)), _connector='OR'), name='ride_rpe_real_in_range'),
        ),
        migrations.AddConstraint(
            model_name='ridesession',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='ride_rating_in_range'),
        ),
        migrations.AddConstraint(
            model_name='ridesession',
            constraint=models.CheckConstraint(condition=models.Q(('cumplimiento__isnull', True), models.Q(('cumplimiento__gte', 0), ('cumplimiento__lte', 100)), _connector='OR'), name='ride_cumplimiento_in_range'),
        ),
        migrations.AddField(
            model_name='cyclisttypeprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cyclist_type_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cyclisttypeprofile',
            index=models.Index(fields=['user', 'tipo_sesion'], name='cyclist_typ_user_id_ed943f_idx'),
        ),
        migrations.AddConstraint(
            model_name='cyclisttypeprofile',
            constraint=models.UniqueConstraint(fields=('user', 'tipo_sesion'), name='unique_cyclist_type_profile_per_user'),
        ),
    ]
