# Generated by Django 6.0.5 on 2026-09-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling', '0002_cyclisttypeprofile_plannedride_narracion_fallback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyclistprofile',
            name='n_rides_baseline',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cyclistprofile',
            name='fuente_baseline',
            field=models.CharField(choices=[('test_20min', 'Test de 20-30 min declarado'), ('historial', 'Estimado de salidas registradas'), ('manual', 'Editado a mano'), ('cold_start', 'Sin datos — provisional')], default='cold_start', max_length=20),
        ),
    ]
