# Generated by Django 6.0.5 on 2026-05-14 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('patron_movimiento', models.CharField(choices=[('empuje_horizontal', 'Empuje horizontal'), ('empuje_vertical', 'Empuje vertical'), ('jale_horizontal', 'Jale horizontal'), ('jale_vertical', 'Jale vertical'), ('sentadilla', 'Sentadilla/Cuádriceps'), ('bisagra', 'Bisagra/Cadena posterior'), ('core', 'Core'), ('cardio', 'Cardio/Metabólico'), ('movilidad', 'Movilidad/Flexibilidad')], max_length=30)),
                ('musculos_primarios', models.JSONField(default=list)),
                ('musculos_secundarios', models.JSONField(default=list)),
                ('equipamiento', models.JSONField(default=list)),
                ('dificultad', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='intermedio', max_length=20)),
                ('contraindicaciones', models.JSONField(default=list)),
                ('bilateral', models.BooleanField(default=True)),
                ('es_compuesto', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'exercises',
                'ordering': ['patron_movimiento', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='UserAdaptationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sesiones', models.IntegerField(default=0)),
                ('rpe_bias', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cumplimiento_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rating_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('volumen_tolerado_semana', models.IntegerField(blank=True, null=True)),
                ('patron_preferido', models.CharField(blank=True, max_length=30)),
                ('semanas_carga_consecutivas', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_adaptation_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserExerciseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_nombre', models.CharField(max_length=200)),
                ('patron_movimiento', models.CharField(blank=True, max_length=30)),
                ('veces_realizado', models.IntegerField(default=0)),
                ('rpe_promedio_real', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rpe_promedio_target', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cumplimiento_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rating_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('ultima_vez', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_exercise_profiles',
                'unique_together': {('user', 'exercise_nombre')},
            },
        ),
    ]
