# Generated by Django 6.0.5 on 2026-05-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_exercise_useradaptationprofile_userexerciseprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='gif_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='exercise',
            name='imagen_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
