# Generated by Django 6.0.5 on 2026-05-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_exercise_media_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionfeedback',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
