# Generated by Django 6.0.5 on 2026-05-15 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0004_dailycheckin_daily_check_user_id_968392_idx'),
        ('users', '0002_userinjury'),
        ('workouts', '0004_nullable_feedback_notas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', '-fecha'], name='sessions_user_id_453603_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', '-created_at'], name='sessions_user_id_06dff6_idx'),
        ),
        migrations.AddIndex(
            model_name='userexerciseprofile',
            index=models.Index(fields=['user', '-veces_realizado'], name='user_exerci_user_id_75a970_idx'),
        ),
    ]
