# Generated by Django 6.0.5 on 2026-05-18 16:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0012_alter_sessionfeedback_cumplimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContraindicationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('body_zone', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('leve', 'Leve'), ('grave', 'Grave')], max_length=10)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'contraindication_categories',
                'ordering': ['body_zone', 'severity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Libre', 'Libre'), ('Máquina', 'Máquina'), ('Cable', 'Cable'), ('Accesorio', 'Accesorio'), ('Ninguno', 'Ninguno')], max_length=50)),
                ('is_gym_only', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'equipment_items',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('anatomical_group', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'muscle_groups',
                'ordering': ['anatomical_group', 'name'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='coaching_cues',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='error_risk',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='exercise',
            name='rest_seconds_default',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='set_duration_seconds',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='space_required',
            field=models.CharField(blank=True, choices=[('minimo', 'Mínimo (≈1 m²)'), ('medio', 'Medio (2–4 m²)'), ('amplio', 'Amplio (>4 m²)')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='systemic_fatigue',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='exercise',
            name='technical_level',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='patron_movimiento',
            field=models.CharField(choices=[('empuje_horizontal', 'Empuje horizontal'), ('empuje_vertical', 'Empuje vertical'), ('jalon_horizontal', 'Jalón horizontal'), ('jalon_vertical', 'Jalón vertical'), ('sentadilla', 'Sentadilla/Cuádriceps'), ('bisagra', 'Bisagra/Cadena posterior'), ('core_antiextension', 'Core — antiextensión'), ('core_antirrotacion', 'Core — antirrotación'), ('core_antiflexion', 'Core — antiflexión lateral'), ('cargada', 'Cargada/Movimiento olímpico'), ('locomocion', 'Locomoción/Transporte de carga'), ('aislamiento', 'Aislamiento muscular')], max_length=30),
        ),
        migrations.CreateModel(
            name='ExerciseContraindication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('contraindication', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exercise_links', to='workouts.contraindicationcategory')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contraindication_links', to='workouts.exercise')),
            ],
            options={
                'db_table': 'exercise_contraindications',
                'unique_together': {('exercise', 'contraindication')},
            },
        ),
        migrations.CreateModel(
            name='ExerciseEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exercise_links', to='workouts.equipmentitem')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_links', to='workouts.exercise')),
            ],
            options={
                'db_table': 'exercise_equipment',
                'unique_together': {('exercise', 'equipment')},
            },
        ),
        migrations.CreateModel(
            name='ExerciseRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('harder', 'Más difícil'), ('easier', 'Más fácil'), ('unilateral_version', 'Versión unilateral'), ('equipment_alternative', 'Alternativa de equipo'), ('variant', 'Variante')], max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('source_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_source', to='workouts.exercise')),
                ('target_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_target', to='workouts.exercise')),
            ],
            options={
                'db_table': 'exercise_relationships',
                'constraints': [models.CheckConstraint(condition=models.Q(('source_exercise', models.F('target_exercise')), _negated=True), name='exercise_no_self_reference')],
                'unique_together': {('source_exercise', 'target_exercise', 'relationship_type')},
            },
        ),
        migrations.CreateModel(
            name='ExerciseMuscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primario', 'Primario'), ('secundario', 'Secundario'), ('estabilizador', 'Estabilizador')], max_length=20)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muscles', to='workouts.exercise')),
                ('muscle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exercise_links', to='workouts.musclegroup')),
            ],
            options={
                'db_table': 'exercise_muscles',
                'unique_together': {('exercise', 'muscle')},
            },
        ),
    ]
