# Generated by Django 6.0.5 on 2026-05-21 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0015_calendarevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeloadTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('programmatic_week4', 'Deload programático (semana 4)'), ('rpe_elevated', 'RPE elevado'), ('doms_persistent', 'DOMS persistente'), ('load_drop', 'Caída de carga'), ('sleep_deficit', 'Déficit de sueño'), ('strength_plateau_peak', 'Plateau de fuerza en bloque pico'), ('adherence_drop', 'Caída de adherencia'), ('caloric_deficit_fatigue', 'Fatiga por déficit calórico severo')], max_length=30)),
                ('action_taken', models.CharField(blank=True, choices=[('deload_applied', 'Deload aplicado'), ('days_reduced', 'Días reducidos'), ('ignored_by_user', 'Ignorado por el usuario')], max_length=20)),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'deload_triggers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('hipertrofia', 'Hipertrofia'), ('fuerza', 'Fuerza'), ('potencia', 'Potencia'), ('salud', 'Salud'), ('perdida_grasa', 'Pérdida de grasa')], max_length=20)),
                ('block_type', models.CharField(choices=[('acumulacion_hiper', 'Acumulación (hipertrofia)'), ('intensificacion_hiper', 'Intensificación (hipertrofia)'), ('acumulacion_fuerza', 'Acumulación (fuerza)'), ('intensificacion_fuerza', 'Intensificación (fuerza)'), ('realizacion_fuerza', 'Realización (fuerza)'), ('fuerza_base', 'Fuerza base (potencia)'), ('potencia_especifica', 'Potencia específica'), ('pico_potencia', 'Pico de potencia'), ('salud_general', 'Salud general'), ('densidad_alta', 'Densidad alta (pérdida de grasa)'), ('preservacion_muscular', 'Preservación muscular'), ('transicion', 'Transición'), ('deload', 'Deload')], max_length=25)),
                ('week_number', models.PositiveSmallIntegerField(default=1)),
                ('is_deload', models.BooleanField(default=False)),
                ('next_session_is_deload', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'training_cycles',
            },
        ),
        migrations.RenameIndex(
            model_name='calendarevent',
            new_name='calendar_ev_user_id_bec901_idx',
            old_name='cal_ev_user_fecha_idx',
        ),
        migrations.AddField(
            model_name='deloadtrigger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deload_triggers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingcycle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_cycles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deloadtrigger',
            name='training_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deload_triggers', to='workouts.trainingcycle'),
        ),
        migrations.AddIndex(
            model_name='trainingcycle',
            index=models.Index(fields=['user', 'is_active'], name='training_cy_user_id_2db6c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingcycle',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_active_training_cycle_per_user'),
        ),
    ]
