# Generated by Django 6.0.5 on 2026-05-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0016_periodization_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycoachinsight',
            name='fragmento',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dailycoachinsight',
            name='modo',
            field=models.CharField(choices=[('empty', 'Sin sesiones'), ('first', 'Primera sesión'), ('building', 'Construcción (2-6 sesiones)'), ('full', 'Completo (7+ sesiones)')], default='full', max_length=20),
        ),
    ]
