# Generated by Django 6.0.5 on 2026-05-29 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0017_daily_coach_insight_modo_fragmento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySaludo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('saludo', models.TextField()),
                ('insight', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_saludos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_saludos',
                'unique_together': {('user', 'fecha')},
            },
        ),
    ]
