# Generated by Django 6.0.5 on 2026-05-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0018_dailysaludo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionfeedback',
            name='molestias',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
