# Generated by Django 6.0.5 on 2026-06-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0019_sessionfeedback_molestias'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='generacion_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='tokens_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='tokens_out',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='uso_fallback',
            field=models.BooleanField(default=False),
        ),
    ]
