# Generated by Django 6.0.5 on 2026-06-05 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0020_session_generacion_ms_session_tokens_in_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='origen',
            field=models.CharField(choices=[('ia', 'IA'), ('coach', 'Coach')], db_index=True, default='ia', max_length=10),
        ),
    ]
