# Generated by Django 6.0.5 on 2026-06-22 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0004_runnerprofile_runningplan_plannedrunsession_and_more'),
        ('workouts', '0022_exercise_add_creado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='session_photos/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='runs.runsession')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='workouts.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'session_photos',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='session_pho_user_id_ff4025_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('session__isnull', False), ('run_session__isnull', True)), models.Q(('session__isnull', True), ('run_session__isnull', False)), _connector='OR'), name='session_photo_exactly_one_owner')],
            },
        ),
    ]
