# Generated by Django 6.0.5 on 2026-06-22 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0023_sessionphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGenerationCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_generation_counts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_generation_counts',
                'indexes': [models.Index(fields=['user', 'fecha'], name='daily_gener_user_id_990f5b_idx')],
                'unique_together': {('user', 'fecha')},
            },
        ),
    ]
