# Generated by Django 6.0.5 on 2026-06-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0024_dailygenerationcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='fin_ejercicios',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
