# Generated by Django 6.0.5 on 2026-07-10 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0026_sessionphoto_image_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionexercise',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_exercises', to='workouts.exercise'),
        ),
    ]
