# Generated by Django 5.2.15 on 2026-07-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0026_sessionphoto_image_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="generacion_error",
            field=models.TextField(blank=True, default=""),
        ),
    ]
