# Generated by Django 5.2.15 on 2026-07-05 00:29

import devices.fields
from django.db import migrations


def encrypt_existing_prompts(apps, schema_editor):
    """Re-encripta el prompt_usado de sesiones ya existentes (guardado en texto
    plano antes de este cambio, con el contexto médico completo del usuario
    embebido). Leer una fila ya migrada simplemente falla a desencriptar (texto
    no-Fernet) y devuelve el valor tal cual — guardarla de nuevo la encripta
    con la clave FIELD_ENCRYPTION_KEY actual. Se salta filas vacías (placeholders
    de generación en curso, ver ai_workout.tasks.generate_session_task)."""
    Session = apps.get_model("workouts", "Session")
    batch = []
    qs = Session.objects.exclude(prompt_usado="").only("id", "prompt_usado").iterator()
    for s in qs:
        batch.append(s)
        if len(batch) >= 500:
            Session.objects.bulk_update(batch, ["prompt_usado"])
            batch = []
    if batch:
        Session.objects.bulk_update(batch, ["prompt_usado"])


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0027_session_generacion_error"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="prompt_usado",
            field=devices.fields.EncryptedTextField(blank=True),
        ),
        # Sin FIELD_ENCRYPTION_KEY configurada, esto es un no-op silencioso
        # (EncryptedTextField degrada a texto plano — ver devices/fields.py).
        migrations.RunPython(encrypt_existing_prompts, reverse_code=migrations.RunPython.noop),
    ]
