# Generated by Django 6.0.5 on 2026-07-25 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0027_sessionexercise_exercise_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='evidence_rationale',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='exercise',
            name='evidence_score',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='exercise',
            name='goal_primary',
            field=models.CharField(blank=True, choices=[('rendimiento', 'Rendimiento'), ('hipertrofia', 'Hipertrofia'), ('salud_general', 'Salud general')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='goal_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='exercise',
            name='injury_risk_profile',
            field=models.CharField(blank=True, choices=[('bajo', 'Bajo'), ('moderado', 'Moderado'), ('alto', 'Alto')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='exercise',
            name='lengthened_bias',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
