# Generated by Django 5.2.15 on 2026-07-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0028_alter_session_prompt_usado"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionphoto",
            name="image_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="sessionphoto",
            name="image_data",
            field=models.TextField(blank=True, default=""),
        ),
    ]
