# Generated by Django 6.0.5 on 2026-07-10 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momentum_cap', models.FloatField(default=8.0, help_text='Cap de |Momentum| en puntos.')),
                ('rendimiento_cap_pct', models.FloatField(default=0.2, help_text='Cap de cambio de Rendimiento por bloque (± fracción).')),
                ('min_feedback_provisional', models.PositiveSmallIntegerField(default=2, help_text='Mínimo de sesiones con feedback para mostrar score provisional.')),
                ('min_repeticiones_ejercicio', models.PositiveSmallIntegerField(default=2, help_text='Mínimo de repeticiones del mismo ejercicio (por bloque) para activar Rendimiento.')),
                ('min_combinaciones_rpe_salud', models.PositiveSmallIntegerField(default=3, help_text='Mínimo de combinaciones de RPE distintas por ejercicio (perfil salud) para ajustar la regresión.')),
                ('ventana_dias', models.PositiveSmallIntegerField(default=28, help_text='Tamaño de la ventana deslizante P1/P0, en días.')),
                ('umbral_neutral_pct', models.FloatField(default=0.02, help_text='Umbral "sin cambio" (± fracción) para el piso neutral de perfiles no-rendimiento.')),
                ('reps_max_e1rm', models.PositiveSmallIntegerField(default=12, help_text='Reps máximas de una serie para incluirla en el cálculo de e1RM.')),
                ('rango_duracion_similar_cardio_pct', models.FloatField(default=0.2, help_text='Rango de "duración similar" (± fracción) para comparar sesiones de cardio Nivel B.')),
            ],
            options={
                'verbose_name': 'Configuración del Zyfit Score',
                'verbose_name_plural': 'Configuración del Zyfit Score',
                'db_table': 'score_config',
            },
        ),
        migrations.CreateModel(
            name='ScoreSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_corte', models.DateField()),
                ('nivel_p1', models.FloatField()),
                ('nivel_p0', models.FloatField(blank=True, null=True)),
                ('momentum', models.FloatField(blank=True, null=True)),
                ('score_final', models.FloatField()),
                ('componentes_json', models.JSONField(blank=True, default=dict)),
                ('perfil_atleta', models.CharField(blank=True, choices=[('rendimiento', 'Rendimiento'), ('salud_general', 'Salud general')], max_length=20, null=True)),
                ('estado_cold_start', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'score_snapshots',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='score_snaps_user_id_e9edcd_idx')],
            },
        ),
    ]
