# Generated by Django 6.0.5 on 2026-05-13 14:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MenstrualCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('duracion_ciclo', models.IntegerField(default=28)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'menstrual_cycle',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('objetivo', models.CharField(blank=True, max_length=200)),
                ('objetivos_multiples', models.JSONField(blank=True, default=list)),
                ('nivel', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='principiante', max_length=20)),
                ('lesiones', models.TextField(blank=True)),
                ('experiencia_deportiva', models.TextField(blank=True)),
                ('estilo_entrenamiento', models.CharField(blank=True, max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('altura', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=20)),
                ('dias_semana', models.IntegerField(default=3)),
                ('horario_preferido', models.CharField(blank=True, choices=[('mañana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], max_length=20)),
                ('nivel_estres', models.CharField(blank=True, choices=[('bajo', 'Bajo'), ('moderado', 'Moderado'), ('alto', 'Alto')], max_length=20)),
                ('tipo_trabajo', models.CharField(blank=True, choices=[('sedentario', 'Sedentario'), ('mixto', 'Mixto'), ('activo', 'Activo')], max_length=20)),
                ('ejercicios_favoritos', models.TextField(blank=True)),
                ('ejercicios_evitar', models.TextField(blank=True)),
                ('rm_sentadilla', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('rm_peso_muerto', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('rm_press_banca', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('rm_press_hombro', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('usa_ciclo_menstrual', models.BooleanField(default=False)),
                ('racha_actual', models.IntegerField(default=0)),
                ('mejor_racha', models.IntegerField(default=0)),
                ('puntos_totales', models.IntegerField(default=0)),
                ('logros', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('gimnasio', 'Gimnasio'), ('casa', 'Casa'), ('exterior', 'Exterior')], max_length=20)),
                ('implementos', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_locations',
            },
        ),
    ]
