# Generated by Django 6.0.5 on 2026-05-14 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInjury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(choices=[('rodilla', 'Rodilla'), ('lumbar', 'Lumbar'), ('hombro', 'Hombro'), ('cuello', 'Cuello/Cervical'), ('cadera', 'Cadera'), ('tobillo', 'Tobillo'), ('muñeca', 'Muñeca'), ('codo', 'Codo'), ('thoracica', 'Dorsal/Torácica')], max_length=20)),
                ('severidad', models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('cronica', 'Crónica')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_injuries',
            },
        ),
    ]
