# Generated by Django 6.0.5 on 2026-05-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='calidad_sueno_habitual',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='condiciones_medicas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='duracion_disponible',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='duracion_minima',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='estilo_coaching',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='horizonte_temporal',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='implementos_perfil',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='lugares_entrenamiento',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='motivacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='motivo_limitacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notas_medicas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='objetivo_secundario',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='razones_abandono',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='tipos_entrenamiento',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
