# Generated by Django 6.0.5 on 2026-05-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_onboarding_extended_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='horario_preferido',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
