# Generated by Django 6.0.5 on 2026-05-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_notif_user_leida_idx_notificatio_user_id_3a45ec_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro')], default='starter', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='plan_renovacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='plan_tipo',
            field=models.CharField(blank=True, choices=[('mensual', 'Mensual'), ('anual', 'Anual')], max_length=20),
        ),
    ]
