# Generated by Django 6.0.5 on 2026-05-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_plan_profile_plan_renovacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='goal',
            field=models.CharField(blank=True, choices=[('hipertrofia', 'Hipertrofia'), ('fuerza', 'Fuerza'), ('potencia', 'Potencia'), ('salud', 'Salud'), ('perdida_grasa', 'Pérdida de grasa')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='goal_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='previous_goal',
            field=models.CharField(blank=True, choices=[('hipertrofia', 'Hipertrofia'), ('fuerza', 'Fuerza'), ('potencia', 'Potencia'), ('salud', 'Salud'), ('perdida_grasa', 'Pérdida de grasa')], max_length=20),
        ),
    ]
