# Generated by Django 6.0.5 on 2026-05-30 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_dias_fijos_profile_nivel_experiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='ImpersonationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('start', 'Inicio'), ('stop', 'Fin')], default='start', max_length=10)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('impersonator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonations_made', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonations_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'impersonation_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='impersonati_created_c75a1f_idx')],
            },
        ),
    ]
