# Generated by Django 6.0.5 on 2026-05-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_is_test_impersonationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pais',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
