# Generated by Django 6.0.5 on 2026-06-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coach_activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('athlete', 'Atleta'), ('coach', 'Coach')], db_index=True, default='athlete', max_length=20),
        ),
    ]
