# Generated by Django 6.0.5 on 2026-06-04 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_profile_codigo_referido'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='codigo_coach',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='CoachAthlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pausado', 'Pausado')], default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartera', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coach_athletes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['coach', 'estado'], name='coach_athle_coach_i_b5e040_idx')],
                'unique_together': {('coach', 'athlete')},
            },
        ),
    ]
