# Generated by Django 6.0.5 on 2026-06-04 17:55

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_profile_codigo_coach_coachathlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachathlete',
            name='config',
            field=models.JSONField(blank=True, default=users.models.default_coach_config),
        ),
    ]
