# Generated by Django 6.0.5 on 2026-06-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_coachathlete_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachathlete',
            name='directiva',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='coachathlete',
            name='directiva_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
