# Generated by Django 6.0.5 on 2026-06-04 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_coachathlete_directiva_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_coach', models.BooleanField()),
                ('texto', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='users.coachathlete')),
            ],
            options={
                'db_table': 'coach_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['link', 'created_at'], name='coach_messa_link_id_cbd859_idx')],
            },
        ),
    ]
