# Generated by Django 6.0.5 on 2026-06-05 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_coachmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(default='Coach Pro', max_length=40)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('pausada', 'Pausada'), ('vencida', 'Vencida')], default='activa', max_length=20)),
                ('slots_incluidos', models.IntegerField(default=15)),
                ('fecha_corte', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coach_subscriptions',
            },
        ),
    ]
