# Generated by Django 6.0.5 on 2026-06-05 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_coachsubscription'),
        ('workouts', '0021_session_creado_por_session_origen'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachAssignedSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('contenido', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada')], default='borrador', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas_de_coach', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workouts.session')),
            ],
            options={
                'db_table': 'coach_assigned_sessions',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['athlete', 'fecha'], name='coach_assig_athlete_421878_idx')],
                'unique_together': {('coach', 'athlete', 'fecha')},
            },
        ),
    ]
