# Generated by Django 6.0.5 on 2026-06-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_coachassignedsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('athlete', 'Atleta'), ('coach', 'Coach'), ('director_tecnico', 'Director técnico'), ('admin', 'Admin de producto')], db_index=True, default='athlete', max_length=20),
        ),
    ]
