# Generated by Django 6.0.5 on 2026-06-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academy_instructor',
            field=models.BooleanField(default=False),
        ),
    ]
