# Generated by Django 6.0.5 on 2026-06-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_user_academy_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='push_token',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
