# Generated by Django 6.0.5 on 2026-07-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_push_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='comunidad',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='tipo',
            field=models.CharField(choices=[('invitacion', 'Invitación a entrenar'), ('insight', 'Insight semanal'), ('alerta', 'Alerta de patrón'), ('logro', 'Logro desbloqueado'), ('reencuentro', 'Reencuentro'), ('community_respuesta', 'Nueva respuesta en tu pregunta de Comunidad'), ('community_mejor_respuesta', 'Tu respuesta fue marcada como mejor respuesta')], max_length=30),
        ),
    ]
