# Generated by Django 6.0.5 on 2026-07-03 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0012_anonymoussession_anonymousprogress'),
        ('users', '0027_notificationpreference_comunidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academy_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembros', to='academy.tenant'),
        ),
    ]
