# Generated by Django 5.2.15 on 2026-07-05 00:29

import devices.fields
import users.fields
from django.db import migrations


def encrypt_existing_medical_data(apps, schema_editor):
    """Re-encripta los datos médicos ya existentes (guardados en texto plano
    antes de este cambio). Leer una fila ya migrada simplemente falla a
    desencriptar (texto no-Fernet) y devuelve el valor tal cual — guardarla de
    nuevo la encripta con la clave FIELD_ENCRYPTION_KEY actual."""
    Profile = apps.get_model("users", "Profile")
    UserInjury = apps.get_model("users", "UserInjury")

    fields = ["condiciones_medicas", "lesiones", "motivo_limitacion", "notas_medicas"]
    batch = []
    for p in Profile.objects.all().iterator():
        batch.append(p)
        if len(batch) >= 500:
            Profile.objects.bulk_update(batch, fields)
            batch = []
    if batch:
        Profile.objects.bulk_update(batch, fields)

    batch = []
    for ui in UserInjury.objects.all().iterator():
        batch.append(ui)
        if len(batch) >= 500:
            UserInjury.objects.bulk_update(batch, ["descripcion"])
            batch = []
    if batch:
        UserInjury.objects.bulk_update(batch, ["descripcion"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_user_academy_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="condiciones_medicas",
            field=users.fields.EncryptedJSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="profile",
            name="lesiones",
            field=devices.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="motivo_limitacion",
            field=devices.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="notas_medicas",
            field=devices.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="userinjury",
            name="descripcion",
            field=devices.fields.EncryptedTextField(blank=True),
        ),
        # Sin FIELD_ENCRYPTION_KEY configurada, esto es un no-op silencioso
        # (EncryptedTextField/EncryptedJSONField degradan a texto plano).
        migrations.RunPython(encrypt_existing_medical_data, reverse_code=migrations.RunPython.noop),
    ]
