# Generated by Django 6.0.5 on 2026-07-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_user_academy_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='intereses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='profesion',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='redes_sociales',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
