# Generated by Django 6.0.5 on 2026-07-05 03:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_profile_ciudad_profile_intereses_profile_profesion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='anios_experiencia_deporte',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='disponibilidad_estudio',
            field=models.CharField(blank=True, choices=[('manana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche'), ('fin_semana', 'Fin de semana'), ('flexible', 'Flexible')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='escuelas_interes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='modalidad_preferida',
            field=models.CharField(blank=True, choices=[('virtual', 'Virtual'), ('presencial', 'Presencial'), ('mixta', 'Mixta')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarding_academia_completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='perfil_deportivo',
            field=models.CharField(blank=True, choices=[('atleta', 'Atleta'), ('profesional', 'Profesional del deporte'), ('entusiasta', 'Entusiasta')], max_length=20),
        ),
    ]
