# Generated by Django 5.2.15 on 2026-07-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_alter_profile_condiciones_medicas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
