# Generated by Django 6.0.5 on 2026-07-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_backfill_onboarding_academia_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='plan_tipo',
            field=models.CharField(blank=True, choices=[('mensual', 'Mensual'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=20),
        ),
    ]
