# Generated by Django 6.0.5 on 2026-07-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_profile_plan_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='usuario',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
