# Generated by Django 6.0.5 on 2026-07-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_profile_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academy_admin',
            field=models.BooleanField(default=False),
        ),
    ]
