# Generated by Django 6.0.5 on 2026-07-23 15:05

import devices.fields
from django.db import migrations


def reencrypt_existing_health_text(apps, schema_editor):
    """Re-guarda los registros con datos preexistentes en texto plano para que
    queden encriptados. Es seguro correrla más de una vez: `EncryptedTextField`
    decodifica lo que ya esté encriptado y lo re-encripta con un nonce nuevo
    (Fernet no es determinístico), y deja pasar tal cual lo que ya esté en
    texto plano si no hay FIELD_ENCRYPTION_KEY configurada (dev sin la key)."""
    Profile = apps.get_model('users', 'Profile')
    UserInjury = apps.get_model('users', 'UserInjury')

    for profile in Profile.objects.exclude(lesiones='', notas_medicas='', motivo_limitacion='').iterator():
        profile.save(update_fields=['lesiones', 'notas_medicas', 'motivo_limitacion'])

    for injury in UserInjury.objects.exclude(descripcion='').iterator():
        injury.save(update_fields=['descripcion'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_user_email_verificado_emailverificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lesiones',
            field=devices.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='motivo_limitacion',
            field=devices.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notas_medicas',
            field=devices.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userinjury',
            name='descripcion',
            field=devices.fields.EncryptedTextField(blank=True),
        ),
        migrations.RunPython(reencrypt_existing_health_text, migrations.RunPython.noop),
    ]
