# Generated by Django 6.0.5 on 2026-07-24 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_contentreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailChangeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_change_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_change_codes',
            },
        ),
    ]
